### ISSUE TITLE
Add how-to for Samba access from different clients

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#110]
Window, Linux and Mac.

**Comment by phillxnet** [comment]
If these howtos are to be more graphical / extensive than what we currently have in samba_ops.rst then we can link to them from there, or have them replace that is currently in samba_ops.rst.

**Comment by phillxnet** [comment]
Linking to related "Connecting to shares via CIFS and NFS" #16 which has comments related to re-ordering the docs so we have client section within each protocol section which is mostly what we have now anyway, including in samba_ops.rst which currently has a non graphical client section. As in #16 I suggest here that we take the contents of now outdated clients.rst which has been partly superseded by the dedicated client sections and put it's contents (if appropriate) into enriching the dedicated client sections within each protocol sections.

**Comment by magicalyak** [comment]
Is this still an issue?

**Comment by phillxnet** [comment]
@magicalyak Yes, things are as stated in my last comment in this issue and the related and linked #16 issue. I'm thinking we ditch the client section and use the best bits if they are not already prescent in the relevant protocol sections. That way when looking at samba section one gets the Rockstor server setup side and client side in one doc. Does seem to be he way things are moving in the docs as is. Older section had client config for all protocols but I think it's better to focus all protocol info in one place, client and server.

Are you considering another doc pr, it would be most welcome. And you have already warmed up on your recent OSX  quickstart section improvements.

My last effort relevant to this was in the AFP protocol doc http://rockstor.com/docs/afp/apple_filing_protocol.html where I documented time machine setup given OSX has now moved to using smb by default for normal file sharing that seemed the most relevant client info / config to put in that protocol section.

**Comment by phillxnet** [comment]
@magicalyak Another example of a more user friendly and graphical presentation of client access within a protocol section is in the sftp protocol section:
http://rockstor.com/docs/sftp/sftp.html#accessing-a-sftp-share

**Comment by phillxnet** [comment]
@magicalyak If you do decide to chip in on this one as well please note your intentions here to try and avoid overlap with other contributors. Cheers. That way others will see it's already in hand.

**Comment by FroggyFlox** [comment]
@phillxnet , I just had a look at what would need to be done for this as I agree with your idea of taking elements of `clients.rst` and integrate them into each service's page if they would improve things there.

We have 3 services: Samba, NFS, and SFTP.
We have 2 locations (currently): `clients.rst` and each service page.
We have 3 clients OS: Linux, MacOS, and Windows.

We should thus have documentation on the combinations of 3 services x 3 clients OS.

**Samba**:
- *Linux*: graphical instructions in `clients.rst`, but text only in service page: Merge the two pages.
- *MacOS*: graphical instructions in `clients.rst`, but text only in service page: Merge the two pages.
- *Windows*: nothing in `clients.rst`, but text only in service page: Add graphical instructions in service page.

**NFS**:
- *Linux*: nothing in `clients.rst`, nothing in service page: Add graphical instructions in service page.
- *MacOS*: nothing in `clients.rst`, nothing in service page: Add instructions in service page. Does recent MacOS support a GUI-way to do that or is it only command line?
- *Windows*: nothing in `clients.rst`, nothing in service page: a quick online search seems to indicate that although Windows 10 supports mounting an NFS share, it might require quite some work (activating a service, editing the Windows registry, manual mounting, ...).

**SFTP**:
- *Linux*: nothing in `clients.rst`, but graphical instructions in service page: Nothing to do.
- *MacOS*: nothing in `clients.rst`, but graphical instructions in service page: Nothing to do.
- *Windows*: nothing in `clients.rst`, but graphical instructions in service page: Nothing to do.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for assessing our current state on this.

Agreed re proposal. I think it will all be a little more straight froward then. And having service and client in same area saves on bouncing around trying to get a config together.

> * Does recent MacOS support a GUI-way to do that or is it only command line?

I'm not really sure. I no longer have access to my prior dated instance of MacOS to check either.

For the NFS windows section I say we just link to a good guide as if it's so tricky it's not likely to be a common config anyway. We can always add to it later.

**Comment by FroggyFlox** [comment]
> I'm not really sure. I no longer have access to my prior dated instance of MacOS to check either.

I'll try to find some time to see if mine is still in a usable state and whether it still is relevant as it's far from the most recent version. We can always leave it as a "Coming soon" or point to other resource to do it... it seems to be supported so there must be something along those lines.


> For the NFS windows section I say we just link to a good guide as if it's so tricky it's not likely to be a common config anyway. We can always add to it later.

Yeah... that's my thought as well. It seems Samba would be the recommended way over NFS anyway, so we can also add such note.

Thanks for the feedback!

**Comment by phillxnet** [comment]
Closed by recent work by @FroggyFlox

**Comment by FroggyFlox** [comment]
@phillxnet, recent forum discussion reminded me of this issue... I think we might want to re-open it and actually work on it. I started looking at what would need to be done (see list of to-dos above), but had forgotten about it.

Let me know if you're ok with re-opening it.

**Comment by phillxnet** [comment]
@FroggyFlox Reopened. Apologies I may have jumped the gun on this one. I had thought we were already there with you last major re-arrangement.

Agreed re forum thread. Thanks for the prompt/correction on this one.

**Comment by phillxnet** [comment]
Added to our milestone but mainly to keep it in the for-front so we don't miss it again.

**Comment by FroggyFlox** [comment]
Thanks! And no worries, I too didn't realize.

I agree with you on putting it on the V4 stable release milestone list as it is a critical part of the documentation in my opinion so it should be of high priority.

**Comment by FroggyFlox** [comment]
To-do list:

- [ ] Update Samba service configuration docs in `services.rst` to include screenshot and further details on settings and options, for instance (linking to samba wiki for `smb.conf` options.
- [ ] Update creation of a Samba export with graphical instructions detailing user permissions, for instance, as well as the different options we offer during the creation of a Samba export.
- [ ] Link to `howtos.rst` section on accessing a Samba share from the `samba_ops.rst` page (creation of a Samba export).
- [ ] Add graphical, step-by-step instructions on accessing a Samba share from Windows using manually entering path in address bar.
- [ ] Add graphical, step-by-step instructions on accessing a Samba share from Windows using "Map network drive"
- [ ] Add graphical, step-by-step instructions on accessing a Samba share from Windows using "Add network location".
- [ ] Accessing from Linux: merge text documentation from `services.txt` to graphical instructions in `clients.rst`.
- [ ] Accessing from MacOS: merge text documentation from `services.txt` to graphical instructions in `clients.rst`.
