### ISSUE TITLE
CLI documentation

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#14]

**Comment by phillxnet** [comment]
@schakrava given the CLI interface is currently deprecated / broken should I remove reference to it from the docs; we can always pick them back out from the git history when / if it gets the attention it needs?

**Comment by schakrava** [comment]
@phillxnet That would be very helpful and appreciated by at least a few users as you may have seen in the forums. Thank you!

**Comment by phillxnet** [comment]
@schakrava I am working on this pull request now and will be done shortly.

**Comment by phillxnet** [comment]
@schakrava OK pull request ready.

**Comment by phillxnet** [comment]
@schakrava since this is merged now I propose closure?
