### ISSUE TITLE
Raid5/6 recovery documentation is incorrect and/or out of date

### ISSUE THREAD

**Issue by Fantastitech** [rockstor/rockstor-doc#142]
I've just finished a couple of pretty major recovery operations and I noticed, after much research that the documentation for data recovery on RAID5/6 arrays had inaccuracies, out of date information, and unnecessary redundancies.

## Mount command
Step 1 and step 12 instruct to mount the pool with:

     # mount /dev/sda /mnt2/mypool

However BTRFS will not mount an array with a missing, failed, or otherwise unmountable drive in a RAID5/6 array without passing the `degraded` mount option. A user with an unmountable drive would not be able to get past step 1 and step 2 does not make any sense in context as it could be run before step 1 to determine if a device is missing or not in which case step 1 would not work.

## Double rebalancing
Step 3 says to delete the failed device, which in a RAID5/6 array will trigger a rebalance to rewrite the parity information for the new amount of drives. In the case of this document, that brings the array down to 3 drives. In step 13 and 14 the user is instructed to add the new device then manually trigger a second rebalance. This puts additional wear on the drives, increases the chance of catastrophic failure, doubles the length of the entire procedure, and if there is not enough space on the array to accommodate the new parity data it will fail.

A much more practical procedure would be to add the new drive to the pool, then delete the failed/missing device. Since failed devices can cause kernel panics, the most sane solution is to remove the failed device from the system completely, mount degraded, add the new device, then delete missing devices which will trigger a single rebalance rebuilding parity information with the new drive.

## Redundant RAID5 and RAID6 sections.
There is a section for RAID5 data recovery, then a second section for RAID6 which just describes that it's the same procedure as RAID6. It would be much more clear, clean, and concise to include information about RAID5 and RAID6 in the same section.

------

I've rewritten the RAID5/6 recovery documentation to correct these issues, clarify some details, and added an extra troubleshooting step for unmountable arrays in the event of superblock issues that prevent a mount command from finding existing drives.

**Comment by phillxnet** [comment]
@Fantastitech Well done on your improvements here by way of your associated pr. Since this has now been merged and published are you content for this issue to be closed?
Please feel free to do so if you are; ie as Fixed by #143 
Cheers.

**Comment by Fantastitech** [comment]
Yep, everything looks great. Thanks.

**Comment by schakrava** [comment]
Thank you!! for your contribution.
