### ISSUE TITLE
Add a BTRFS primer

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#146]
A brief primer for those that have not used BTRFS before, or not know much about it.
Highlight use cases, features and cutting-edge nature of some features like raid5/6.
Highlight upcoming features and how they are planned to be integrated into Rockstor.

**Comment by phillxnet** [comment]
Of note here btrfs feature wise is bad disk notification and hot spare pending features which are intertwined.
Also we have the pending addition of inband / inline deduplication.
And of course planned built in crypto.
There are also plans to use the existing facility within metadata to categorise / utilise devices differently according to their relative speed.
