### ISSUE TITLE
Create MAC OS X section for USB creation

### ISSUE THREAD

**Issue by magicalyak** [rockstor/rockstor-doc#149]
for quickstart.rst it would be good to have a Mac OS X option.  This should be possible using dd and the diskutil command.  I am testing this now but following this guide (with the only change being umount should be called through diskutil (diskutil umount /dev/disk2s2) and not directly) and it appears this does work well on El Capitan (latest).

http://osxdaily.com/2015/06/05/copy-iso-to-usb-drive-mac-os-x-command/

If this is of use I can try to post results here or do a pull request on the rst and modify

**Comment by magicalyak** [comment]
http://osxdaily.com/2015/06/05/copy-iso-to-usb-drive-mac-os-x-command/

**Comment by phillxnet** [comment]
@magicalyak That would be most welcome. I've tested a similar method on 10.11.1 a while back and posted example output in the following forum thread which may be of use:
https://forum.rockstor.com/t/problems-creating-bootable-installation-usb-flash-drive-on-a-mac/884/8

If you are sure of the method you propose and have tested it then I say you go straight to the pull request. If the assembled instructions are a little bit long for that purposefully short section you could do a dedicated section akin the the others linked there; like the gnome-disks-howto link. That way we can keep that section short and not skimp on the details. Ie put a specific link in that quick start section. Just a suggestion though but gives you more freedom to be thorough and paste example diskutil output and the like.

Thanks and hope it goes well.

Note there is the "Contributing to Rockstor documentation" at:-
http://rockstor.com/docs/contribute_documentation.html
that may also be of help.

**Comment by magicalyak** [comment]
Great, so far I have only "made the USB" not installed from it.  I have had some disk errors and am going to reinstall Rockstor and re-import the two pools I have using this USB.  If it works I'll do the pull request.

**Comment by magicalyak** [comment]
Just succeeded with the install, I'll update the rst tomorrow :)

**Comment by phillxnet** [comment]
@magicalyak Given your pull request to address this has now been merged and published, #151, are you game to close this as Fixed by #151?

**Comment by magicalyak** [comment]
Yes

**Comment by phillxnet** [comment]
@magicalyak Cheers, given you are the original author you are also able to close. Please go ahead and close if your are game. Thanks for fleshing this one out by the way.
