### ISSUE TITLE
link to btrfs status page

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#155]
Thanks to @Yoshi in the following forum thread for drawing attention to this. In the past few days a btrfs status page has emerged which breaks down the stability status of various btrfs features; it would be good to link to this from for example our FAQ and pool sections.

Please update the following forum on this issues resolution:
https://forum.rockstor.com/t/btrfs-raid-5-6-warning/1712/9

**Comment by jakieu** [comment]
Some progress, hopefully merged in Linux 4.10...

https://www.phoronix.com/scan.php?page=news_item&px=Btrfs-RAID5-RAID6-Fixed

**Comment by Dbzs** [comment]
@phillxnet Is this closed by the #176 issue I just added the link for, or is this the same link added to another spot in the documentation?

**Comment by phillxnet** [comment]
@Dbzs Yes nice find. If you could add an additional closes line (on it's own) to your just submitted pull request original text (ie edit it like before) with this issue number then you can do another 2 in one. You appear to be doing double time these days :)

Marking this issue as:

Duplicate of #176

as per @Dbzs finding/suggestion.

Apologies for my miss management of these issues but I think we are getting them more into shape now.

**Comment by Dbzs** [comment]
@phillxnet what can I say, I'm lazy so I'm all for getting a two-for whenever possible.  If folks aren't going to do due diligence before submitting your at a huge disadvantage trying to keep these all straight.

**Comment by phillxnet** [comment]
@Dbzs My fault really but it will certainly be easier as we get the backlog down. I'm going to do another work through our really old rockstor-core issues soon as they are way too numerous and there are bound to be duplicates / out-of-date candidates in there by now. Plus it definitely impacts on the value of an issue tracker if it becomes bloated. Some systems simply auto close issues past a certain date if they have had no traction. I don't thing we can go there but I do hope to shrink all repos to a clearly manageable set of well defined and currently relevant issues.

**Comment by Dbzs** [comment]
@phillxnet I've looked at some of the older ones thinking working from oldest to newest made sense, but some of them were a little vague and I wasn't sure how applicable they still were.  So I changed my approach to knocking out well defined ones first, then when we're out of quick kills, I can start digging in and defining the more nebulous ones, but that may take some back and fort to make sure I understand the intent.
