### ISSUE TITLE
add reciprocal link to reinstall page from config backup page

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#156]
Thank's to @k0nsl in issue https://github.com/rockstor/rockstor-core/issues/1497 for highlighting the lack of a link from the http://rockstor.com/docs/config_backup.html#configuration-backup-and-restore
page back to the related http://rockstor.com/docs/reinstall/reinstall.html#reinstalling-rockstor page.
This would be a useful link back for those ending up on config backup and save page first, when they were researching re installation procedures.

**Comment by phillxnet** [comment]
While editing the http://rockstor.com/docs/reinstall/reinstall.html#reinstalling-rockstor page it would be better to reference the config save and restore at page the beginning as well as at the end. This would further help prevent the loss of prior configuration details.

**Comment by Dbzs** [comment]
@phillxnet I can take this one on next, but quick question on the http://rockstor.com/docs/config_backup.html#configuration-backup-and-restore status.  The top of the page has bold text saying this is beta not recommended for production environments.  Is that still valid?

**Comment by phillxnet** [comment]
@Dbzs Thanks for continuing to steam in on the docs issues backlog. Much appreciated.

Re the "... beta testing ..." note, good point but yes I think we do need to leave that in place as although this feature has been implemented for quite some time and has received some bug fixes, it's still not all that comprehensive: i.e. it still doesn't save all the items in the second list; which is enough I think to keep that beta tag in place.

We have however had a distinct lack of reported issues recently in this area, at least pertaining to stable, so I think what we have is good; but still not that comprehensive so if used without reading these docs it might still fall short of reasonable expectations. It could do with more attention really but as always there are many such cases.

**Comment by Dbzs** [comment]
@phillxnet saw your note on the 2 issue question I will take care of both under this branch.  One more house keeping question, I notice most of the pages with photos are in a folder with the rst and png files all located in that folder.  Currently the config_backup.rst and associated png files are all living in the main branch.  Will creating a folder and putting all the appropriate files in it cause problems, or would it be welcome house keeping?  Any gotchas I need to watch out for or naming conventions I need to be aware of?  Thanks for your continuing guidance, I hope I'm saving more work than I'm making for you.

**Comment by phillxnet** [comment]
> Will creating a folder and putting all the appropriate files in it cause problems

It will if the appropriate index file is not also updated. I.e. for sftp, ups_setup, and rock-ons, which are in their own directory, we have:
```
   sftp/sftp
   ups-setup/ups_setup
   docker-based-rock-ons/overview
```
in index.rst.

Where as for the older entries, when we were still using a flat layout, we have:
```
config_backup
```
So as far as I can remember it's just a matter of also updating the appropriate index file, but note also that the howtos have the following link in index.rst:
```
   howtos
```
but that the top level howtos.rst file is itself an index file containing the likes of:
```
   pre-install-howto/pre-install-howto
   reinstall/reinstall
```
So as long as the relevant index is updated I think it should be OK. You can always check the navigation and display function of the result via the python webserver trick executed in the root of the docs once you have compiled them via Sphinx.
```
pushd ./_build/html; python -m SimpleHTTPServer; popd
```
Ctrl+C to exit the above.

And yes this would be a welcome change, assuming it doesn't break anything, as it's then easier to keep things separated. One caveat with larger structural changes such as this is the potential knock-on with others working on the same file at the same time. But I don't think we have that concern here currently.

As per naming conventions I'd follow what you see in the more modern doc entries.

Well done for upping our game here by the way.

You are definitely helping here, I'm just a little tied up with some back-end build stuff that I have to work-out/get-done that is limiting the time I can spend on the docs with you but hopefully we can muddle through and make it so.

Thanks again for your contributions and ideas and anything you can get done is a bonus all around.

**Comment by Dbzs** [comment]
So I moved the files on my local system and ran a make html and got some
errors about the new folder not being in toctree, so I found the toctree,
and it looked like the entry was their so I reran without any errors, and
things checked out in the browser.  I just went back and added
config_backup/config_backup in place of config_backup in the index.rst file
and had another successful build and ops check so I'll enter the pull
request. Thanks again for the help, I'd love to help with code, but the
last language I had any proficiency in was FORTRAN 77.

**Comment by phillxnet** [comment]
@Dbzs OK great. So if you first delete the "_build" and do a fresh Sphinx build and all is well, just to double check, then it should be good. Sometimes it's necessary to wipe this directory just to double check a build is clean from scratch. Maybe that was what the errors related to.

As per code contribution you are more than welcome and if you can do Fortran (or any other language come to think of it) then you can do python; the majority of what Rockstor is written in.There's a bunch of javascript for UI elements but it's mostly Python. I'd definitely say take a look at some of the code and see what you think. Some parts are admittedly a little opaque but most of it is quite clean and a fair bit of it is also documented as well, working on this as I go along. Same process re code contribution as docs but with a little more review and a lot more setup. Also you will absolutely require a linux system to test the code on, this could be a VM of course and is mostly done on prior Rockstor installs where everything is updated and docker-ce is installed as that is what the stable branch uses. The docs on this have some issues but are mainly OK, bar some requirements to use https rather than git protocol from when I last looked.

**Comment by Dbzs** [comment]
Deleted _build and had another good make html run so went ahead with the
pull request.  I did just pull out an old laptop and install openSUSE leap
15 on it, but not sure I have the time to dig into all the prep work for
code contributions.  Think I'll satisfy myself with being a productive doc
contributor.
