### ISSUE TITLE
Connecting to shares via CIFS and NFS

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#16]
From
1. Linux (nfs and cifs)
2. windows (nfs and cifs)
3. mac (nfs and cifs)

**Comment by phillxnet** [comment]
Some sections now have duplication re client access ie:-
The new SFTP doc has client access instructions as does the AFP section and the Samba/CIFS doc also has some non illustrated client instructions.
But we also have a dedicated doc on the same ie clients.rst which is currently fairly incomplete.
I suggest we rationalize this and have client sections in each protocol which seems to be how things are going. Ie remove clients.rst and use the material to flesh out the sections that need it.

**Comment by phillxnet** [comment]
Closing as all info / ideas here are duplicated and with more engagement in:
"Add how-to for Samba access from different clients" #110
which also has Linux and Mac references.
