### ISSUE TITLE
VirtualBox install demo video link broken

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#160]
In the "Quick evaluation using a virtual environment" sub section of the Installation section this video link fails with:
"This video is private"
the link used is:
https://www.youtube.com/watch?v=00k_RwwC5Ms
We probably need an updated install video anyway: ie one based on the soon to be released:
3.8.16 stable.

**Comment by schakrava** [comment]
Thanks @phillxnet , you are right. We should update the video. But for now, I made it public, not sure why it was private in the first place.

**Comment by phillxnet** [comment]
@schakrava  Cheers. I've now updated the forum post which lead to this discovery.
