### ISSUE TITLE
add link in redundancy profiles section to wiki status page

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#176]
Currently we have a "Please see the btrfs wiki for up to date information on all btrfs matters." this should be enhanced to include a link to the more specific btrfs wiki raid levels status page:
https://btrfs.wiki.kernel.org/index.php/Status

**Comment by Dbzs** [comment]
@phillxnet This one looks pretty straight forward and simple, add a link to the status page in addition to the existing link.  Am I missing anything?

**Comment by phillxnet** [comment]
@Dbzs Hello again. Yes I think this one is fairly simple. That status page use to be a little behind the times but of late it has been maintained better, hence creating this issue to use it as a canonical link for redundancy status info to back-up our own comments re different raid levels.

**Comment by Dbzs** [comment]
@phillxnet OK, I'll take care of it.

**Comment by phillxnet** [comment]
@Dbzs Thanks. Much appreciated. My current background 'mission' is now starting to wrap up so I'm hoping to tend to all your pending pull requests there after.

It's encouraging to have the docs on the move again.

**Comment by Dbzs** [comment]
@phillxnet happy to help.
