### ISSUE TITLE
missing links in Basic Concepts section

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#183]
It would be good to ensure that there is a link from each of the sections on the Basic Concepts page to the more detailed specific sections, ie Disk to the Disks page, Pool to the Pools page etc.

**Comment by Dbzs** [comment]
@phillxnet I think I can take this one on next.  Do you want to check my homework on the Rufus update before start this one?

**Comment by phillxnet** [comment]
@Dbzs If you are game then great. Thanks a lot.

As per your prior pr if you do as you did in that one I think you will be golden.:)
Just remember to branch from master again as this doesn't overlap and isn't co-dependant so should not be a problem. And of course make sure you work in an issue specific branch as you did with the last pr.
Super.

**Comment by Dbzs** [comment]
@phillxnet quick question on this one.  I added links for all except Secure Shell and Smart Manager because I don't think there is a detail page to link to.  There is a page for SMART disk drive info, but based on the description I don't think that's what you're describing.  If you can point me in the right direction I'll add those links, other wise I can create a pull request as is. Thanks.

**Comment by phillxnet** [comment]
@Dbzs Thanks for your efforts here. One point I'm afraid I should have clear up first is that web url links of the type you have used are a little fragile in comparison to the 'internal' type links. Look to other links of the kind that reference internal doc labels.

I.e. a label will be something like
```
.. _powerstatus:
```
and an internal link to that is made thus:
```
:ref:`powerstatus`
```

These particualar examples can be seen via GitHub (where it doesn't know how to use them as they haven't been processed by Sphinx yet) in the following link:

https://github.com/rockstor/rockstor-doc/blob/master/disk-power-down/disk_power_down.rst

and if you press the raw button there you can then see the targets at the top of each section.

Then when Sphinx processes the doc into html (or whatever else) all links are resolved and we get a degree of checking done on them and it's more portable.

I think it's a restructured text type thing but not sure.

Apologies if I didn't clear this up with you first. 

If you are still game there should be existing links for the pages / sections you are linking to. If not then they will have to be made.
I.e. in your first example of Disks we have:

```
..  _disks:
```
visible via the raw view on GitHub via:

https://raw.githubusercontent.com/rockstor/rockstor-doc/master/disks.rst

Also make sure that at the end of all edits (or during to help with validation) that you re-run Sphinx's
```
make html
```
as you go. Sometimes it's necessary to delete the directory it creates in your local copy so it can re-create from scratch. Also the tip on running a python webserver (in the docs) while you go is also good. You can then check the links are linking back to your actual version.

Hope that helps and isn't too discouraging.

Apologies again for not clarifying this with your. We only use those kinds of links for external web pages; such as you did in your prior rufus pull request.

I hope this hasn't discouraged you. You can if you wish simply make the changes, commit them to your git and push and they will appear in this pr.

**Comment by phillxnet** [comment]
Those internal links are actually quite fancy as they pickup on the target text and present it within the link. Give it a go on one first and see if it works for you.

**Comment by Dbzs** [comment]
Phil,
  No worries, not discouraged, I just need to actually go through the full
sphinx install and get it working.  I was able to do the rufus update all
inside the editor on the github site.  I was surprised when it rendered,
but I wasn't going to argue.  Sounds like I'm not going to get away with
that using internal links so it will slow me down a bit, but hopefully not
too long.

Are my assumptions that there is no SSH or Smart Manager page to link to
correct, or do they exist, and I'm not making the connection?
Thanks for the insight,
Del

**Comment by Dbzs** [comment]
@phillxnet @schakrava I think I got the link thing figured out using :ref: and I used the link in the last line of the rock-ons paragraph as my style template to add links to the other sections.  Only 2 sections I can't do are SSH, and Smart Manager, because there is no page to link to, but Smart Manager sounds a lot like Dashboard.  So if you agree, I can update the title of the Smart Manager section to Dashboard and link to the Dashboard page.  I'll hold off on the pull request until I hear back on that idea.

**Comment by Dbzs** [comment]
@phillxnet @schakrava Is this the same issue as 84 and 139?  If so any actions required?

**Comment by phillxnet** [comment]
@Dbzs Well done with chipping away at this.
Re: Smart Manager, it's actually an internal name for an element of Rockstor that works in the background so I'd leave that for now. And yes we don't have a SSH details section such as is described there.
Are you able to check your work via Sphinx, if so a paste of what it said would be good. Also a quick functional check of your links via the python webserver trick. No worries otherwise, just means a reviewer has a bit more to do.
Re issue #139, I've just closed it as a duplicate of this one.
Re issue #84 "update concepts doc" lets leave that for the time being until we get a little more content update on this concepts page.
Well spotted and not the reference used here (# then the issue number, if it's in the same repo, and GitHub will turn it into a link.

Thanks for the housekeeping pointer by the way. You seem to be on a roll. Much appreciated. We do need to work through our backlog and this is definitely helping.

**Comment by Dbzs** [comment]
Happy to finally find a way to contribute, I've been leaching for a couple years, and love the system.  I sort of cheated today, I was working from my company machine so checked my work in an online sphinx editor https://livesphinx.herokuapp.com/ and it all rendered properly, but no report to attach.  Still don't have the web server set up, hoping to find time this weekend to take care of that.  

I'll keep chipping away, I noticed you had an issue open for broken links to the Sphinx info.   I found those as I did my research, so I'll probably make that the next issue I tackle.

**Comment by phillxnet** [comment]
@Dbzs Thanks for your extended efforts here. Much appreciated. And nice find re the online sphinx editor. Maybe you could pop a link into the Sphinx info section if you do end up doing that issue.

I will endeavour to review your pull requests shortly and can run a Sphinx check on them when I do so no worries there. Well done on working the git complexities out by the way.

Thanks again for your efforts and glad your like the system. Your contribution to the Sphinx section / issue would of course also be appreciated.

**Comment by phillxnet** [comment]
@Dbzs Thanks for another nice set of improvements. Much appreciated. The absence of these links was rather embarrassing really.

Closing this issue as fixed by @Dbzs in pr #195 

Remember that you can delete your issue specific branches via the button presented in the now closed pull request. Helps to keep things tidy in your GitHub clone, git wise, if you have fewer branches.
