### ISSUE TITLE
Add Data Import and Reinstalling Rockstor links to Configuration Backup and Restore

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#184]
Thanks to erik_llorente in the following forum thread for highlighting this issue. Although we have a 'Data Import' section at the end of the 'Reinstalling Rockstor' section which in turn links to the pool/share/clone/snapshot import mechanism provided via the 'Disks' page we do not have a similar convenience line within the 'Configuration Backup and Restore' section. It is proposed that this would make for a valuable addition to the 'Configuration Backup and Restore' section as such a process is often associated with a re-install.

Note that similarly it would be helpful to also link, from the 'Configuration Backup and Restore' section, to the existing 'Reinstalling Rockstor' Howto. These suggested links/new sections should aid in discover-ability re data import given the higher position within the table of contents that the 'Configuration Backup and Restore' occupies.

**Comment by Dbzs** [comment]
@phillxnet This looks like a close cousin of issue 156 that I'm starting on, I'm thinking I ought to just cross link both pages in the process and close these both, or did I miss something?  I already opened a branch specific to 156, but I could close it and open a new one referencing both issues.  What's the proper good housekeeping approach?

**Comment by phillxnet** [comment]
@Dbzs I think you are fine carrying on as you are and then when you come to do your pull request, you can simply put 2 closes lines which will indicate that the one pull request address both issues. This issue will then be linked to the pull request that closed it. Hope that's clear enough. I.e. it can get messy and cumbersome to have to reference both issues in each commit or pull request so given they are both fairly small, if you are happy managing them both in a single pull request, then great. As long as the final pull request indicates this issue as well we have a record of what change ended up address what issue which is the main thing really.
So yes carry on as is in your 156 branch and just reference this via an additional closes line.

Thanks for your diligence in these pull requests by the way. It definitely helps to keep track of things as we go along. Hoping to merge all pending and publish all recently merged soon.

**Comment by phillxnet** [comment]
Closing as fixed by #199 by @Dbzs 
Thanks @Dbzs 
Closing this manually as it looks like your double entry of issue numbers in the referenced pr caused the second to be ignored.
