### ISSUE TITLE
typo re sftp exported share mount point

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#185]
Thanks to forum member asood in the following thread for highlighting this issue. In sftp.html we incorrectly reference a mount point as beginning /mnt3... this should be /mnt2... and represents a simple typing mistake on the path.

Please update the following forum thread with this issues resolution:
https://forum.rockstor.com/t/rsync-to-a-rockstor-share/4619/8

**Comment by Dbzs** [comment]
this looks like another one I can handle.  Change 3 to 2 sounds pretty straight forward.  I'll add a recommendation for a open source windows SFTP client as well.  If I'm not taking too many liberties I'd like to reorder the wording and links in the 4 bullet points under creating an SFTP share so it flows from the general page to the detailed section.  I read the reference forum discussion and don't see any other changes to this page, but if I'm missing something, or there are other suggestions while I'm in there, I'm all ears.

**Comment by Dbzs** [comment]
Scratch the SFTP client recommendation, I was going to link to WinSCP, but I see it's already done at the bottom of the page.

**Comment by phillxnet** [comment]
@Dbzs Hello again, and thanks for tackling yet another docs issue.
Re the re-order were you thinking:
Create Pool (if needed)
Create User
Create Share
Export share.

I think my original ordering or user, pool, share, export was to keep the storage elements together and emphasise that this is a user based access. As per the bullet points prior. Makes a similar amount of sense to keep the share related elements together (above) however.

The SFTP system as currently implemented must have the share owned by the accessing user, this is not the case with all our other export methods. In all others users simply need access, and don't need to be the actual owner.

Yes the WinSCP poped up in my searches as a popular windows choice, plus it was a GPLv3 thing, but it was some time ago. No screen shots in that bit as I don't run windows so just did text.

Rather embarrassing this issues main typo was left so long really.

**Comment by Dbzs** [comment]
My thought on reordering was not the bullets themselves, but the links inside the bullet, for instance.
- Add a Rockstor user to use in the SFTP authentication process, see the User configuration section.
The first link to add user, fall's below the second link to the User configuration page.
When I followed the links it didn't make sense to me to link lower in the page first and higher second.  I was suggesting flipping the order to link higher first and lower second. I'm happy to leave as is, I'll defer to your preference.   I installed WinSCP for fun, and it's a nice tool, I can add a screen shot if you think it helps.

**Comment by phillxnet** [comment]
@Dbzs Re the links within the bullet points. Ok I get what you are saying now. I think this would work if the first link text was only 'Rockstor user', ie "Add a **Rockstor user** to  use in the SFTP ..." as then the link text relates more closely to it's target which was what I was after. That way, as you say, the second link is then to the more specific 'Add user' subsection and the first it just about Rockstor users generally. Go for it.

Re images from WinSCP, I think that would definitely help. I'm planning on adding a Linux Dolphin (from the KDE desktop) section as well some time. That way we have both main linux desktop environments covered and the OSX and Windows (given you proposed images) Desktop examples.

Thanks, and nice suggestions.

**Comment by Dbzs** [comment]
All right, sounds like we're in sync on the bullets, and I'll get some
WinSCP captures along the lines of what you already have for Linux and
OSX.  It seemed to me if we were making changes might as well do any other
house keeping that makes sense at the same time.  I think I would have felt
guilty if I had just changed a 3 to a 2 and made the pull request.
