### ISSUE TITLE
broken sphinx install link / instructions

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#191]
The "Installing Sphinx"  sub section of "Contributing to Rockstor documentation"(contribute_documentation.html) has a broken link:

http://www.sphinx-doc.org/latest/install.html

this could be replaced with:

http://www.sphinx-doc.org/en/master/usage/installation.html

and to add robustness we could also link to Sphinx's home page by changing our existing "Sphinx official documentation" text into a link to:

http://www.sphinx-doc.org/en/master/#

and rather than the existing "Follow the documentation here(link)" we cold have have, "Details of how to install Sphinx is covered in their **Get it**(link) subsection." Which also removed the questionable practice of linking the 'here' word.

**Comment by phillxnet** [comment]
Given a successful 'make html' can only be accomplished with the addition of the following modules:

sphinxcontrib-fulltoc
sphinxcontrib.youtube

we should also add a section for their install, although a python2 version for sphinxcontrib.youtube is provided there is an issue if using the python3 version of Sphinx in that there is an upstream issue of no upload currently available for sphinxcontrib.youtube on PyPi.

See https://github.com/shomah4a/sphinxcontrib.youtube/issues/8

for how to install direct from github to get the python3 fixed version of 0.2.0 ie:
```
pip3 install --user git+https://github.com/shomah4a/sphinxcontrib.youtube.git@404e8f17c2505333a0781a62800c5a8a08ba3c52
```
where the python3 equivalent for sphinxcontrib-fulltoc is:
```
pip3 install --user sphinxcontrib-fulltoc
```
We could include these directions to allow for both python2 and python3 variants of Sphinx to be used.

**Comment by Dbzs** [comment]
Just opened a branch to start working this one.

**Comment by Dbzs** [comment]
@phillxnet just submitted a pull request that address these comments and adds a little more info awaiting feedback or recommendations.

**Comment by phillxnet** [comment]
@Dbzs Thanks again for your efforts here. Commented in the pr after a quick look and will try to get to a proper review soon. Nice additional changes by the way.

**Comment by Dbzs** [comment]
@phillxnet Saw your comment on the auto close syntax, happy to fix.  To get back to editing, do I close the pull request, make the change and reopen?

**Comment by phillxnet** [comment]
@Dbzs No need to close the pull request, you can simply edit your pull request text in place:

![edit-pull-request-text](https://user-images.githubusercontent.com/2521585/52733098-c742a680-2fb9-11e9-9133-6f4fdc5be781.png)

via the 3 dots top right.

**Comment by phillxnet** [comment]
The text you added to the docs re "Fixes #issue" looked fine, it was the the pull request text really. Hence the irony in your actual submitted docs entry:

"... if you add a "Fixes #number-of-issue" on it's own line ...".

Thanks. Trying not to be too picky here but also want to try and keep our repositories maintained and these little auto features help with tidying up after ourselves. So again nice touch poping that in the docs for others. Hadn't though of it myself as it goes.

**Comment by Dbzs** [comment]
Fixed. 
I has to reread your comment.  I thought I had it wrong in the doc revision.  My comment entry was actually "helped" by auto complete on the github page.

**Comment by Dbzs** [comment]
Happy for the feedback, I'd rather develop good habits now than break bad ones later

**Comment by Dbzs** [comment]
Did I paste the sphinx output in the right place, or should I have included that differently?

**Comment by phillxnet** [comment]
@Dbzs The Sphinx output was just dandy. Thanks.
