### ISSUE TITLE
add circleci sphinx build with test deployment option for doc admins

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#202]
The free plan of circleci, along with GitHub integration, should enable us to provide a test Sphinx build of 'master plus proposed pull requests' upon pull request submission. It would also be nice if a test publish of the docs could be accomplished upon successful / no errors Sphinx 'make html'. The latter would best be implemented, to avoid prank use, via manual request on the linked circleci control panel. This should ease testing for doc admins by providing an online 'render' of the resulting changes.

It is proposed that this online 'test view' render be published in a sub-directory of the existing docs with the directory named after the pull requests GitHub number. I.e. once requested the resulting docs could be viewed at:
rockstor.com/docs/1111
where 1111 is the number of the associated pull request. Formatting elements could then be discussed against the example 'real life' render without either tester or submitter having to maintain a docs development environment.

Ideas / contributions welcome.

**Comment by phillxnet** [comment]
Also consider GitHub Actions as an alternative for the same function.

**Comment by FroggyFlox** [comment]
That looks like a really neat feature, @phillxnet!

The documentation seems indeed like a prime candidate for that and I particularly like the idea of not having to build the PR to see the final render of the changes. Furthermore, combined with GitHub suggestions feature, it'll make PR review quick and easy to adapt if needed!

**Comment by FroggyFlox** [comment]
Hi @phillxnet,

I've been itching to give a try at this issue for a while now and I've finally bitten the bullet. I've created a test PR in my fork to illustrate what I could get using Github Actions:
- the pull request in question can be found at: https://github.com/FroggyFlox/rockstor-doc/pull/4
- the included checks are at: https://github.com/FroggyFlox/rockstor-doc/pull/4/checks

Upon **the creation of a pull-request**, this action will run 2 jobs:
- `build_docs`: install sphinx, sphincontrib-fulltoc, and run `make html`
- `check links`: install sphinx, sphinxcontrib-fulltoc, and run `make linkcheck`

We can thus see if the PR builds, and whether it introduced broken links (we still need to clean up our links, but that's another issue).

Now, I'm wondering something about:

> It would also be nice if a test publish of the docs could be accomplished upon successful / no errors Sphinx 'make html'. The latter would best be implemented, to avoid prank use, via manual request on the linked circleci control panel. This should ease testing for doc admins by providing an online 'render' of the resulting changes.
> 
> It is proposed that this online 'test view' render be published in a sub-directory of the existing docs with the directory named after the pull requests GitHub number. I.e. once requested the resulting docs could be viewed at:
> rockstor.com/docs/1111
> where 1111 is the number of the associated pull request.

I don't know if one can manually trigger an action that would do such thing... still need to be explored.

We can also have another action that will build and deploy to production once a push is made on the master branch (should be focus of a different issue/PR, though).

**Comment by phillxnet** [comment]
@FroggyFlox This is great, well done.

> I don't know if one can manually triger an action that would do such thing... still need to be explored.

No, we are likely going to have to continue to resource our own internal build system for this final rendering check. It was probably a little bit of a reach anyway given the priviledges that would be required. I was hoping however that the actions might enable some kind of temporary web server hosting arrangement to test basic sites. Maybe in time this will appear, likely with limited access to those logged in with merge access or something.

> We can also have another action that will build and deploy to production once a push is made on the master branch (should be focus of a different issue/PR, though).

Nice idea but I'm not keen on given GitHub admin access to our Web server now I think about it. But yes, this is for another issue and would first need to have rendering checked, ideally, anyway prior to pushing to production.

**Comment by FroggyFlox** [comment]
Thanks...

re your first point, I actually just realized there might be an option to manually trigger, and even restrict that to users with right access. See my edit above:
> EDIT: it actually seems to be easily doable, and even restricted to users with write access:
> https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-on-github

The question of temporary web server hosting remains opened, though... Maybe the Github pages? There seems to be a lot of available actions made just for that.

**Comment by phillxnet** [comment]
@FroggyFlox Given my comments elsewhere it may be that this issue is now defunct, especially given it's now misleading reference to circleci etc. And the consequent mission creep (me again). So feel free to close and re-open a more focused issue on your current work which would help with clarity anyway. I.e. Github action to sanity check sphinx build or the like.

**Comment by FroggyFlox** [comment]
@phillxnet, agreed on closing this issue as we are now using an alternative mechanism to do that. We can always open a new dedicated issue for your test deployment idea when/if we figure out a clean way to do so.
Hope it's ok with you; feel free to re-open if you prefer.
