### ISSUE TITLE
normalise docs youtube channel and document accordingly

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#203]
Some embedded YouTube links are from the "Rockstor" channel, eg http://rockstor.com/docs/pools-btrfs.html#creating-a-pool
while others are from the "rockstorinc" channel.

It is suggested that we normalise the preferred channel and stick to that channel. This will require all required videos are copied to the chosen channel.

Once complete we should document the required channel to submit any proposed video inserts. This note could be located in our existing:
contribute_documentation.rst

Currently the vast majority of videos are on the "rockstorinc" channel with the "Rockstor" channel having only 7 videos in total.

**Comment by FroggyFlox** [comment]
@phillxnet , I'm going to close this one as it is now deprecated by #309.
I hope you're ok with it but feel free to re-open it if you prefer to keep it.
