### ISSUE TITLE
Remove now redundant BTSync entries

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#208]
As the existing Resilio Sync Rock-on has superseded our prior BTSync Rock-on, where the latter has now been removed from the rockons-registry, see pr:

Remove the BTSync rock-on from registry.
https://github.com/rockstor/rockon-registry/pull/200

it is proposed that we remove the BTSync Rock-on write-up accordingly.

**Comment by FroggyFlox** [comment]
Thanks for thinking about that, @phillxnet, I forgot about this.

Ideally we would replace that with a new write-up for Resilio Sync, but in the meantime, should we simply delete the BTSync section?

**Comment by phillxnet** [comment]
Agreed would be nice to have a new Resilio Sync write up but it may not be popular enough to warrant the effort. So:

> in the meantime, should we simply delete the BTSync section?

I'd say so. And we have a link to this repo within the docs in the "Rock-ons Available by default" so that's something. But we could at some point update the "Rock-ons without write-ups" as that might be good for those assessing Rockstor from the docs first to see if their used applications are available.

**Comment by FroggyFlox** [comment]
> But we could at some point update the "Rock-ons without write-ups" as that might be good for those assessing Rockstor from the docs first to see if their used applications are available.

Very good point... This needs to be harmonized too anyway, as some of these link to the docker image on hub.docker while others link to the main project's website.

**Comment by phillxnet** [comment]
> This needs to be harmonized too anyway, as some of these link to the docker image on hub.docker while others link to the main project's website.

Are yes, nice catch. My apologies, my fault on that one. I think we can agree these should be to the upstream projects as per our main Rock-on links.
