### ISSUE TITLE
[Rock-ons] Add write-up for YouTrack official rock-on

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#211]
To fix https://github.com/rockstor/rockon-registry/issues/201, we need to update the YouTrack rock-on to its official image. Notably, this rock-on has specific pre-install requirements related to share ownership that would need to be documented prior to releasing the rock-on.

We would thus need to create a write-up for the **YouTrack official** rock-on with instructions on:
1. How to create shares.
2. Create a specific user (UID 13001).
https://www.jetbrains.com/help/youtrack/standalone/youtrack-docker-installation.html#create-and-configure-directories
Create user:
- name: any
- UID: 13001
- GID: leave default (needs to be 13001).

3. Set owner of shares in step 1 to the user created in step 2.
4. Instructions on upgrade from previous versions (create a backup, and then restore in new instance): link to YouTrack's documentation as they include detailed step-by-step instructions: https://www.jetbrains.com/help/youtrack/standalone/upgrade-with-docker-image.html#youtrack-zip-msi-to-docker

**Comment by phillxnet** [comment]
@FroggyFlox 

> * GID: leave default (needs to be 13001).

We may have to be more specific on this one as in our pending openSUSE variants the GID's differ per user to those found in our CentOS offerings.

**Comment by FroggyFlox** [comment]
Oh very good point, thank you for pointing it out as I didn't think of it. I'll make sure to detail that one needs to create the group first (with GID 13001) and then the user as part of this group.
