### ISSUE TITLE
Add some basic debugging steps if something goes wrong.

### ISSUE THREAD

**Issue by nkhare** [rockstor/rockstor-doc#22]
It would be also good tell users what information to send when contacting for support.

**Comment by phillxnet** [comment]
Note that this could also include how to retrieve logs via scp or via sftp with reference to the sftp docs section but using the root user to retrieve the logs via a gui client.

**Comment by phillxnet** [comment]
An example of more content that may be appropriate in this docs addition might be:
https://forum.rockstor.com/t/help-recovering-web-ui-from-crash-after-share-changes/1191/2?u=phillxnet

**Comment by phillxnet** [comment]
Addressed by our recent dev doc section update.

Closing as:
Fixed by #321
