### ISSUE TITLE
[Config Backup & Restore] Move Rock-on configuration as supported

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#227]
In preparation for the next rockstor release in which rock-ons will be supported in the config backup & restore feature, we should also update the corresponding section of our documentation:
https://github.com/rockstor/rockstor-doc/blob/master/config_backup/config_backup.rst

Indeed, we currently have the rock-on configuration listed as _planned_, but we should move it to the list of _supported_ configs.

For reference on the feature itself, see the now-merged PR:
https://github.com/rockstor/rockstor-core/pull/2100

We might also take the opportunity to further emphasize that restore a previous backup will **replace** any existing config that is currently supported by the feature (I believe this is the case for all). We already do explain that it will restore the system to a previous state, but we might want to further emphasize that fact with an additional message contained within a "warning block". 

We could also provide further explanation on the restore logic for some features. For services, for instance, all those who were turned ON at the time of backup will be turned back ON after restore. Similarly, for rock-ons, they will all be turned back ON, etc...

@phillxnet , do you think that would be overkill?

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for opening this issue and for it's detail.

> @phillxnet , do you think that would be overkill?

No, I think that's more along the lines of a MVP :)
