### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#24]

**Comment by phillxnet** [comment]
A general update of old (pre-redisign) screen grab images might fit in this one.

**Comment by phillxnet** [comment]
@schakrava This issue is due for closure as the indicated commit has been merged. Unless it is a catch all but then it can never be closed!.Is that the intention? Thanks.

I favour cleanups going in along side named issues myself as less clutter in the end. Can work both ways though.

**Comment by phillxnet** [comment]
Closing as lacking specificity and we need to reduce our backlog to more easily see specific requirements.
