### ISSUE TITLE
update minimum system requirements re regular USB keys

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#241]
Thanks to forum member b8two for highlighting our messaging failure re regular (read slow) USB key as system disk. It appears from this feedback that it can be interpreted that our current documentation wording does not make clear that absolute function failure will result when an inappropriate system disk is used (Web-UI and underlying support system time outs), i.e. in the case of a regular USB keys use rather than our current wording of:

> 16GB drive for Rockstor's system disk; if USB key use only fast variants (32GB+ SSD recommended).

This issue's author proposes that we add, akin to the VM note, something along the lines of the following:

> Rockstor cannot work reliable when installed on regular USB keys. Only fast variants, or preferably HDD, SSD class devices, are appropriate.

**Comment by b8two** [comment]
Hi Philxnet,

I think that USB2.0 interface is also the limitaiton regarding USB type installation. 
Hence requirements should include USB 3.0+

**Comment by phillxnet** [comment]
@b8two First off, thanks for chipping in on this issue. Much appreciated.

Can you confirm that your experience with even fast USB 3.0 keys used in USB 2.0 ports resulted in timeouts? From a quick re-read of your linked forum post this does seem to be the case. I've used that config myself quite a bit but only really with test machines that really didn't have much work to do anyway. So It may be that once a little more loaded we would start seeing occasional timeouts which is essentially a broken / inadequate setup.

I'm thinking for this issue that we just add that USB 3.0 is recommended. Or maybe strongly recommended or the like.

What wording/stance do you think we should take here? Bearing in mind that some home systems end up very lightly loaded anyway.

Linking to your excellent forum post on this same issue for context (sorry I should have done this in the initial issue creation):
https://forum.rockstor.com/t/usb-2-0-interface-dilemma/7156

**Comment by phillxnet** [comment]
I am currently working on this issue.
