### ISSUE TITLE
Update supported architectures

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#250]
As brought up by @phillxnet during #249's review, we can now update our list of supported architectures to add Arm64:
https://github.com/rockstor/rockstor-doc/pull/249#discussion_r516232077

This change could be done in `faq.rst`, but there might be additional places needing this information updated.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
```
grep -R "x86_64" *.rst
index.rst:Rockstor 4 can be installed on commodity x86_64 and ARM64 hardware.
```

**Comment by phillxnet** [comment]
```
grep -R "Intel" *.rst
faq.rst:requirement is that the system be of a 64bit Intel or compatible architecture.
faq.rst:Intel NUC. We recommend visiting our `Forum <https://forum.rockstor.com>`_ for

```
