### ISSUE TITLE
Remove reference to seemingly deprecated Swish tool

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#252]
In our section on how to access SFTP shares from a Windows client, we link to the Swish tool among other options:
http://rockstor.com/docs/sftp/sftp.html#sftp-access-from-windows

Unfortunately, their latest release dates from June 2013 and the Github page hasn't seen much commits for a few years. It is, for instance, unsure whether it is compatible with Windows 10. As we have already quite a few other options listed, it might be preferable to simply remove our links to Swish (especially considering this is our first option listed).

On a side note, it could be interesting to add FileZilla as another option, as it is a very popular tool (like WinSCP) and is GPLv2.

@phillxnet, any thought on either of these points?

**Comment by phillxnet** [comment]
@FroggyFlox Agreed on both points. No good having a link to an unmaintained project and always good to offer GPL* projects given our own license.

Cheers, and nice find.
