### ISSUE TITLE
Add PGID/UID reference to General Rockon section

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-doc#254]
Since quite a few containers (with and without write-up) have a requirement to enter PGID or UID (especially if they are based on linuxserver.io's templates), should we add a section in the general Rockon section (overview.rst), that either references the UID/PGID section in the rockstor install, or give a couple of ways to obtain that information (the primary one being for the less technical audience and show the WebUI option.
In the Plex write-up we also had a section to create a new Rockon specific user, so that's a question from me whether that should also be noted in this general context (either recap or reference Rockstor section, or reference Plex section on new user creation, etc.).

**Comment by FroggyFlox** [comment]
Good idea, @Hooverdan96 !

After a quick look, it seems that it would be a good fit right after the "Rock-ons root" section. Just a few words should be enough if accompanied by screenshots.
It's also a reminder that we need to update our "Users" section: #8 

Down the line, I'm hoping we'll be able to have a more automated system to look up/select a user in the Rock-on install wizard itself, and even create one on-the-fly if needed. That will be a long way down the road, though.

Thanks a lot for the idea, and let us know if/when you will be taking care of it. If interested, you can have a look at our contribution guidelines for this repository:
http://rockstor.com/docs/contribute_documentation.html#contributing-to-rockstor-documentation

**Comment by Hooverdan96** [comment]
@FroggyFlox  - yep, I started looking on the documentation contribution info already. I will try in the next few days to come up with a draft...

**Comment by Hooverdan96** [comment]
Hi,
@FroggyFlox first try, please have a look. I essentially assume, that somebody that's using command line knows all the ways to get the User info, but this is really for the UI-driven user setting up their first Rock-on ...
