### ISSUE TITLE
Images aspect ratios are not respected

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#258]
Throughout the documentation, most images are displayed with an aspect ratio that does not fit the image's original. As a result, these images appear compressed along their width. This appears contradictory at first to the use of the `:scale:` option of the `.. image::` directive, which should scale down both height and width of the image.

After a quick inspection of the final html code, we can see that while the width and height of the image appear to be properly scaled down, we are hitting the *page* width limit for most of these, which thus results in such a compressed display. For instance:
![image](https://user-images.githubusercontent.com/30297881/103364125-f453b180-4a8a-11eb-9415-effd3f729fa9.png)
In the example above using a `:scale: 80%` option, we can see that:
- the html code does scale down properly: `style="width: 931.2px; height: 602.4px;`
- but the image width hits the page limit: `width: 730px; height: 602.4px;`

Let's thus look at the `.. image::` directive documentation:
https://docutils.sourceforge.io/docs/ref/rst/directives.html#image

> width : length or percentage of the current line width
>     The width of the image. Used to reserve space or scale the image horizontally. As with "height" above, when the "scale" option is also specified, they are combined.
>
> scale : integer percentage (the "%" symbol is optional)
>     The uniform scaling factor of the image. The default is "100 %", i.e. no scaling.

As a result, it appears more appropriate to use the `:width:` option without defining the height to have a proper scaling. Testing this with the same image as in the example above:
**current**:
```
.. image:: rockons_root_share.png
   :scale: 80%
   :align: center
```

**alternative**:
```
.. image:: rockons_root_share.png
   :width: 100%
   :align: center
```
![image](https://user-images.githubusercontent.com/30297881/103364575-2addfc00-4a8c-11eb-95c1-f87298ea7de8.png)

We can see that the image now uses the full width of the page (as instructed by `:width: 100%`), resulting in an image with the same aspect ratio as the original, which looks a lot better.

Of course, this would need to be verified for all images, so implementing this (if accepted) might be better done progressively on a PR-by-PR basis.

**Comment by phillxnet** [comment]
@FroggyFlox Nice find. 
> We can see that the image now uses the full width of the page (as instructed by `:width: 100%`), resulting in an image with the same aspect ratio as the original, which looks a lot better.

I think I remember way back battling with this one so it's nice to have a work around. Always bug me when the images are distorted that way.

> Of course, this would need to be verified for all images, so implementing this (if accepted) might be better done progressively on a PR-by-PR basis.

Agreed. If it looks to be behaving itself after a few trials we could later do a global search replace.

Thanks again for your diligence here. Much appreciated.
