### ISSUE TITLE
[Rock-ons] Add write-up for Scrutiny

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#269]
Thanks to @20design, we now have a rock-on for Scrutiny, a hard drive monitoring program:
https://github.com/rockstor/rockon-registry/pull/261

Due to its many features and relevance to the NAS nature of Rockstor, it would be beneficial to include a proper description of its installation settings as well as a few examples for its use.

**Comment by 20design** [comment]
@FroggyFlox I will gladly help, so you would like to have a clearer description about Scrutiny scope? Can I quote documentation from the office help? Should I provide an example of the config I use in Rockstor or you want an example of the config file for Scrutiny? 
Also, should I put this info in the "Additional information" of the Rockon or the description?

**Comment by FroggyFlox** [comment]
Hi @20design, and thanks a lot for offering your help!

> you would like to have a clearer description about Scrutiny scope?

The intent of these write-ups is mostly to document and illustrate their installation as well as featuring their feature(s) briefly. You can have a look at the most recent one we merged, for instance (#266): 
http://rockstor.com/docs/docker-based-rock-ons/netdata_official.html#netdata-official-rock-on

As you can see these usually make use of screenshots to illustrate any pre-install requirements (creation of shares, user permissions, or any other thing that might be required to do prior to installing the rock-on), and then post-install steps if any. For Scrutiny, there's not much pre-install configuration to make besides the creation of the config share. There is, however, some environment variables to be configured during the rock-on install wizard that could help some slight development in a write-up (what they do, and default recommended setting). As for the post-install steps, we may want to mention what is already listed in the "more_info" field with regards to manually triggering the collection of metrics if desired.

> Can I quote documentation from the office help?
Yes, I usually heavily take advantage of the project's documentation as long as we heavily link to it as a result. What I have in mind when writing these usually is to stay short and sweet and mention the essentials, all while linking to the relevant section of the project's documentation for further details.

> Should I provide an example of the config I use in Rockstor or you want an example of the config file for Scrutiny?
The former should be covered by a simple screenshot of the rock-on install wizard (which could be used to describe the ENV variables as mentioned above). The latter would be perfect, indeed, as long as you don't include any personal information (of course). It's true that the notification feature of Scrutiny could be great to illustrate, for instance, but not a necessity. If you are willing to, I would say go for it as it would be great, but no worries otherwise.

>  Also, should I put this info in the "Additional information" of the Rockon or the description?
That is an excellent question. I've been wondering how to best link to our own documentation from within the Rockstor webUI (such as https://github.com/rockstor/rockstor-core/issues/2263) and these write-ups would be perfect candidates for that. We actually had an idea shared by @Hooverdan96 in the rockstor-core repo (https://github.com/rockstor/rockstor-core/issues/2231) to surface the "More info" information in the list of available rock-ons and I think it's a great way to do that. Feel free to share any feedback or idea you would have on that too ;-) .

Thanks again for all your help and contributions!

**Comment by 20design** [comment]
Alright, I understand now. I am unfortunately unfamiliar with sphinx, but will give it a shot.
Hopefully by the weekend I'll have something :-)

**Comment by 20design** [comment]
Hi @FroggyFlox I didn't finish the document this weekend, but still busy on it. 
Regarding the contribution, should I follow this procedure: http://rockstor.com/docs/contribute_documentation.html#making-changes or I can fork the doc repo and send a pull request?

**Comment by FroggyFlox** [comment]
Hi @20design, no worries!

The procedure detailed in our documentation (to which you linked), essentially describes the command line way to make changes **after** you have forked and cloned the *rockstor-doc* repo locally so I would answer your question with: yes to both.

If you look at the first part of the document to which you linked, you'll see that we describe how to fork and clone the repo to your local machine. It's essentially the same procedure as what you must have done for the *rockon-registry* repo to submit your pull request:
1. on Github, click "Fork" to fork the rockstor-doc repo.
2. clone your fork locally to your machine
3. Make a new branch for this issue
4. Make the changes you want
5. Verify it all works as intended on your machine (by building the docs using Sphinx and browsing locally)
6. Commit your changes, push to your fork
7. Create a pull-request

I believe all of that should be detailed in the doc to which you linked above, but let us know if any point is not clear so that we can improve it if needed. Note also that while we detail the command line procedure (because it is the one thing that is common between all platforms), you can also accomplish all of it using one of the many Git GUI tools that exist.

Thanks again for stepping up with yet another contribution, and let us know if there's anything you need!

**Comment by 20design** [comment]
Hi @FroggyFlox, I have finally done this write-up. Let me know if something must be changed or done differently.
