### ISSUE TITLE
Add documentation for using Sphinx Docker container to make html

### ISSUE THREAD

**Issue by 20design** [rockstor/rockstor-doc#272]
Hello, I propose to add in the documentation how to build HTML using Sphinx docker container: https://github.com/sphinx-doc/docker

**Comment by phillxnet** [comment]
@20design This is a great idea. Thanks for opening this issue.

**Comment by FroggyFlox** [comment]
@20design , thanks a lot, that is a great idea indeed!
@phillxnet , I wonder if we could take advantage of that to trigger some Github Action to test build new PR for rockstor-doc as a result; I would assume triggering a docker container is supported by that.

**Comment by 20design** [comment]
Hi @FroggyFlox the base image of docker-sphinx doesn't contain the `sphinxcontrib-fulltoc` so it must be built. This is supported by Github actions AFAIK, but maybe the image should be published on Docker-hub to avoid building it at each commit? I don't know if it's free or not :-)

**Comment by FroggyFlox** [comment]
Thanks for the clarification.

If running it in a docker container works well, we might want to create our own Dockerfile (basically the one you described in #273) in a separate *rockstor-docker-sphinx* (or better name) that will be used for automatically building the docker image that will be published on Docker Hub and/or Github container registry. I haven't looked at either registry's policies/terms of use in a while--and I know Docker Hub made substantial changes recently--but I believe we should explore the option if it's available to us.
