### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#278]
Due to some changes, we now have a couple of *true* broken links, as well as a few links that trip sphinx's `make linkcheck` that we probably should ignore.

### True broken links
```
(docker-based-rock-ons/scrutiny: line   98) broken    https://github.com/AnalogJ/scrutiny#configuration - Anchor 'configuration' not found
(        services: line  100) broken    https://sssd.io/docs/users/faq.html#when-should-i-enable-enumeration-in-sssd-or-why-is-enumeration-disabled-by-default - 404 Client Error: Not Found for url: https://sssd.io/docs/users/faq.html
```

### Others
The following are reported as *broken* by sphinx's `make linkcheck`, but work upon user click or are simply "placeholder" urls:
```
(docker-based-rock-ons/minio: line   38) broken    http://domain-name:port - Failed to parse: http://domain-name:port
(      contribute: line  370) broken    https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ - HTTPSConnectionPool(host='ariejan.net', port=443): Max retries exceeded with url: /2011/07/05/git-squash-your-latests-commits-into-one/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
(docker-based-rock-ons/overview: line  142) broken    https://bitcoin.com/ - HTTPSConnectionPool(host='www.bitcoin.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000016EAFBB3188>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

The latter "errors" could probably be resolved by ignoring these links upon running linkcheck, by using the `linkcheck_ignore` option:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_ignore

> A list of regular expressions that match URIs that should not be checked when doing a linkcheck build. Example:
> ```python
> linkcheck_ignore = [r'http://localhost:\d+/']
> ```

**Comment by FroggyFlox** [comment]
@phillxnet , one of these problematic links would require some feedback:
> https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

Indeed, the problem with this one (reported by `make linkcheck`) is related to the SSL certificate and thus the user would have to bypass it to access the page:
![image](https://user-images.githubusercontent.com/30297881/123545570-b0362680-d726-11eb-843a-5032c9e74fa9.png)

Although we could ignore this link to get a clean `make linkcheck` result, it might be better to guide the user towards a site without this kind of issue. After a quick search, I found the following:
https://levelup.gitconnected.com/how-to-squash-git-commits-9a095c1bc1fc

What do you think? Let me know if you have a better reference for that one.

**Comment by phillxnet** [comment]
@FroggyFlox Agreed. Lets use the alternative link.
Nice find. I didn't know `make linkcheck` could do this ;).

Not keen on adding any link check bypasses/white-lists if we can help it. They may be seen as a fix-all for any other links with non apparent obvious issues in the future.

**Comment by FroggyFlox** [comment]
Sounds good, I'll replace the link, then.



> Not keen on adding any link check bypasses/white-lists if we can help it. They may be seen as a fix-all for any other links with non apparent obvious issues in the future.

Agreed... That ignore list is intended for links that cannot be successfully checked, such as API etc... In our case, we could use it for one of the problematic links:
> (docker-based-rock-ons/minio: line   38) broken    http://domain-name:port - Failed to parse: http://domain-name:port

... as it isn't a real link; although one could argue that we shouldn't actually present this as a link as clicking on it will inevitably lead to error... might be better suited for a `code` or *italicized* text, actually.
