### ISSUE TITLE
Update samba documentation

### ISSUE THREAD

**Issue by sujeetsr** [rockstor/rockstor-doc#28]
Creating Samba share documentation should be updated to reflect the fact that Samba exports are now created from the sidenav Samba menu item, instead of on the share details page.

**Comment by phillxnet** [comment]
@schakrava I believe this is now done by curtesy of yourself and @vinima via commit:-
https://github.com/rockstor/rockstor-doc/commit/054800e22c05490d695a9573144896f806924783

**Comment by schakrava** [comment]
thanks for the cleanup @phillxnet !
