### ISSUE TITLE
Table of contents is sub-optimal

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#284]
It seems our documentation has grown substantially over the years and led to an overcrowded table of contents. While all the information is available, it might not be presented in the best possible way from a user perspective. Indeed, the table of contents currently include **34 items** which seems too many for a user to quickly find the desired information.
We also have a few instances of duplication of content that could be improved as it can be confusing for the reader.

It is proposed to simplify the current table of content by reorganizing it. It would mostly consist in consolidating similar items into a single main group. For instance, *User interfaces*, *Disks*, *Pools*, *Shares*, etc... could be grouped into a single header in the table of content; their individual page(s) structure would still remain the same, though.

Without a detailed analysis, it appears that reducing the number of first level headers in our table of contents to < 20 would already be a very big improvement. This number is arbitrary, though, as the final number should be decided by the logic that we want to follow for the table of content's organization.

The duplicated content could also be further simplified, although it could be part of a separate PR.

@phillxnet, before we go further into the details of what the new table of content organization could/should be, do you think it is an idea worth pursuing?

**Comment by phillxnet** [comment]
@FroggyFlox Re:

> ... do you think it is an idea worth pursuing?

Definitely. I've thought this myself actually but not gotten around to the issue creation / wording.

An example of an almost completely useless entry: https://rockstor.com/docs/benchmarks.html Otherwise taking up / fogging the top level of navigation. Another that has received zero feedback, at least in my time as maintainer is: https://rockstor.com/docs/analytics.html Again prioritised as a top level member and clouding the navigation of key day-to-day required indexes.

Thanks for creating this issue and giving it some thought. Much appreciated.

We might also re-consider the method/mechanism by which we generate this table of contents / top navigation page within the docs: sphinxcontrib-fulltoc.

**Comment by FroggyFlox** [comment]
> We might also re-consider the method/mechanism by which we generate this table of contents / top navigation page within the docs: sphinxcontrib-fulltoc.

That's an interesting idea/thought. I haven't looked at why we need it, but if we could do without it, it would allow us to not rely on any additional "plugin" and **only** use the `sphinx` package; always good to trim down our dependencies.

**Comment by phillxnet** [comment]
@FroggyFlox 

> and **only** use the `sphinx` package; always good to trim down our dependencies.

Exactly. We ran into an issue a little while back, where our YouTube plugin fell out of repair and one had to install it directly from a pr branch on the unmaintained GitHub repo when using Python 3 I think it was. Anyway in the move to zero cookies on the docs I ended up stripping that out and replacing all YouTube embeds with links. Less fancy but bar easier to maintain. And the simpler we make the docs dependencies the more likely it is we can consider other targets such as pdf or the like. And possibly even it's inclusion in an offline form within a Rockstor install. We have spoken in the past of Web-UI contextual "?" buttons that in turn link to our docs. You have added a number of these already; I believe. These might present a fail over to the offline version if the online one was not available, indicating this fail through to an uncontrolled doc variant. Digressing slightly here of course.

**Comment by FroggyFlox** [comment]
@phillxnet, I've had a better look at this and I think it would be beneficial for the user/reader and for simplifying the main table of contents to follow the Rockstor user interface to group most of the content that is currently describing the user interface anyway. The rest would be grouped when possible, or moved to a more appropriate section. A tentative table of contents would thus be:
```
Table of contents

    Introduction (What is Rockstor?)
	    Feature Overview
            Basic Concepts
	Installation
	    Quick start
	    Pre-Install Best Practices (PBP) (moved from How-tos section)
	    Rockstor’s “Built on openSUSE” installer - Beta release (moved from How-tos section)
	User Interfaces
		Dashboard
		Storage (NEW)
		    Disks
		    Pools
		    Shares
		    Snapshots
		    Replication (was: Share replication)
		    File sharing (NEW)
		        Apple Filing Protocol (AFP)
		        Network File System (NFS)
			Samba/CIFS
			Secure File Transport Protocol (SFTP)
		System (NEW)
		    Services
		    Identity (NEW)
			Users (was: User configuration)
			Groups (NEW)
			Access keys (NEW)
		    Network (was: Network configuration)
		    Scheduled Tasks
		    Software update (NEW, integrate "Update Channels")
		    Appliances (was: Multiple Rockstor appliances)
		    SSL Certificate (NEW)
		    Config Backups (was: Configuration Backup and Restore)
	            Email alerts (was: Email Notifications)
		    Logs Manager (NEW)
		    System shell (NEW)
		Rock-Ons (was: Rock-ons (Docker Plugins))
        Data loss Prevention and Recovery in Rockstor
        UPS / NUT Setup
        Accessing Shares from Clients
        How-tos
        Community Contributions
        Product FAQ
        Support
        Analytics (Remove as deprecated)
        Benchmarks (Remove)
```

Thanks for letting me know what you think when you get a chance.

**Comment by phillxnet** [comment]
@FroggyFlox This looks like a major improvement. Things have definitely gotten out of hand on this front.

In establishing a partial parallel between Web-UI and docs, structure wise, shouldn't the NUT page be inside services. Or if that is getting a little deep, and assuming services is just about services. We put NUT under system.

Nice idea this. Also it looks like, with all these new sections. We may want to do this in stages. As each new section may well required some additional into wording or the like.

Shorter names are also preferred. We can always add sub-titles to those less familiar with such lingo as "Config". Or ensure first words in section contain the full version of such words. For example I once spoke to a computer user, english native, who did not understand the term "Default" which was extensively used in their UI but not, obviously, in their day-to-day activities / communication.

One concern I do have is that we should try not to break old links. Not sure if this is going to be the case, but for example there are may references to our https://rockstor.com/docs/update-channels/update_channels.html and these changes would presumably break these. It might also be argued that this could be maintained as a top level referenced but linked to from inside the proposed "Software update (NEW, integrate "Update Channels")" thus preserving it's top level. And given it's importance and likely high frequency of look-up and old links that may be prudent. Also note that it is linked to from within the Web-UI. I'm not keen on managing an ever growing Apache redirect for such things as I know that is another way to handle this. Most other pages are far less key and don't yet have internal Web-UI links from existing installs. But it may be that if we are only talking about the TOC then such movements don't necessarily affect the urls. Sorry bit involved in other stuff currently but just wanted to ensure we don't break existing Web-UI embedded links for all existing installs.

**Comment by FroggyFlox** [comment]
> In establishing a partial parallel between Web-UI and docs, structure wise, shouldn't the NUT page be inside services.

Agreed... That's how I listed it at first but then I thought it may deserve its own section as its documentation is very detailed and it represents a nice feature to highlight. I was thus thinking of leaving the UPS/NUT description in *Services* rather simple but referring to the detailed UPS/NUT existing page.


> Shorter names are also preferred. We can always add sub-titles to those less familiar with such lingo as "Config". Or ensure first words in section contain the full version of such words. For example I once spoke to a computer user, english native, who did not understand the term "Default" which was extensively used in their UI but not, obviously, in their day-to-day activities / communication.

Good point, and a good goal to keep in mind in our upcoming improvements to the documentation.



> One concern I do have is that we should try not to break old links.

Oh excellent point; I didn't think of that. There seems to be a couple extensions that would take care of (even automatically) redirect pages moved to different sections for us; but it would add one more extension while we're trying to limit our use of extension. I noticed https://github.com/sphinx-contrib/redirects and https://github.com/wpilibsuite/sphinxext-rediraffe (the latter being more up-to-date, active, and seemingly quite powerful); it might be worth adding that. I'll try to see if a there's a way to do so without adding an extension.

Thanks a lot for the precious feedback!

**Comment by FroggyFlox** [comment]
I was curious so I had a little try with the `sphinxext.rediraffe` extension; it seems to work rather well! Here's what I did:

1. install it with `pip install sphinxext-rediraffe`
2. edit `conf.py`:
```python
# -- Options for sphinxext.rediraffe --------------------------------------
rediraffe_redirects = "redirects.txt"
rediraffe_branch = "master"
```
3. Create the file `redirects.txt`
4. Move `update_channels/update_channels.rst` to `System/software_update.rst`
5. Run the automatic diifcheck write builder: `sphinx-build -b rediraffewritediff . _build/rediraffe`
```
sphinx-build -b rediraffewritediff . _build/rediraffe
Running Sphinx v4.1.0
(okay) Renamed file "update-channels/update_channels.rst" has been redirected to "System/software_update.rst" in your redirects file!
building [mo]: targets for 0 po files that are out of date
building [rediraffewritediff]: targets for 0 source files that are out of date
looking for now-outdated files... none found
no targets are out of date.
build succeeded.(...)
```
The `redirects.txt` file now contains:
```
"update-channels/update_channels.rst" "System/software_update.rst"
```
6. Building the html yields:
```
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.1.0
(...)
build succeeded, 6 warnings.

The HTML pages are in _build/html.
Writing redirects...
(good) update-channels/update_channels.html --> System/software_update.html

Build finished. The HTML pages are in _build/html.
```

Now, let's run a local server and test it: `cd _build/html && python -m http.server 8000`
Open a browser and access the following URL that should be redirected: `http://localhost:8000/update-channels/update_channels.html`
... we are indeed redirected to `http://localhost:8000/System/software_update.html`

**Comment by phillxnet** [comment]
@FroggyFlox Re:

> Agreed... That's how I listed it at first but then I thought it may deserve its own section as its documentation is very detailed and it represents a nice feature to highlight. I was thus thinking of leaving the UPS/NUT description in _Services_ rather simple but referring to the detailed UPS/NUT existing page.

OK, that works. And I'm OK with that. Just trying to get stuff out from top level. But UPS was put in the top level initially, by me, as I also thought it was a key feature. Interestingly enough it was a feature/capability I added to Rockstor in my early days as I had a few months earlier ruled out using Rockstor as it had no Web-UI UPS / NUT configuration. I ended up returned a few months later and put it in as I couldn't find another DIY NAS option that appealed to me that did have UPS integrated already :).

So OK, we leave this as a top/featured element, as it's good to encourage UPS use anyway on central servers at least.

> I had a little try with the `sphinxext.rediraffe` extension;

That looks like a really nice find. And if it's easily available then great. Agreed another extension is potentially a backward step but it's open source at least. And we can definitely use it for this re-structuring.  The auto config bit via git renames is cute. Not sure quite how robust that's going to be in the long run or during major reworks. But if we keep an eye on what we move/rework then we can always pop the redirect in as required manually. We could consider hosting an openSUSE package for this in our OBS repos to avoid having to use the pip version i.e. python3-sphinxcontrib-rediraffe as I don't find a single instance of it via: https://build.opensuse.org/search?search_text=python3-sphinxcontrib-rediraffe&search_for=0&name=1&attrib_type_id= Or whatever the 'proper' name would be.

It's a little extra fragility thought, but potentially worth it with allowing us to redirect. Plus if it ends up bit-rotting away we have a central record of what we need to redirect via web server config it if comes to that.

Thanks for looking into and proving this fix. Does rather free us up for all manner of potential changes on the docs.

**Comment by FroggyFlox** [comment]
> So OK, we leave this as a top/featured element, as it's good to encourage UPS use anyway on central servers at least.

Sounds good; I'll do that, then.




> It's a little extra fragility thought, but potentially worth it with allowing us to redirect.

I agree that relying on an extension does add a layer that can fail, but the more I think about it, the more I think it's worth it in this case as it removes the fragility we currently have with regards to broken links (especially considering we currently do not have a good way to automatically check for that in our other repos). I'm thus a bit more kin to give it a try with: if it works well for a substantial re-organization of our docs such as we're planning, then it's a good test!
Of note, it seems the UBports project, which I believe to be of a substantial size, does seem to use it for this exact reason. Their doc describes that rather well, page 40:

> However, people link to our documentation from many sources that we do not control.  Blogs, websites, and other documentation  sites  can  direct  people  here  using  links  that  they  may  never  update.   It  is  a  terrible  experience  to follow a link from a different site and land on a 404 page, left to your own devices to find your way in restructured documentation. We use a tool called Rediraffe to avoid this bad experience. 

https://readthedocs.org/projects/docsubportscom/downloads/pdf/latest/


> We could consider hosting an openSUSE package for this in our OBS repos to avoid having to use the pip version i.e. python3-sphinxcontrib-rediraffe as I don't find a single instance of it

Oh that's a good idea! It seems to be potentially rather simple too as per the openSUSE wiki on packaging python apps:
https://en.opensuse.org/openSUSE:Packaging_Python#The_fast_and_automated_way
That made me rather curious and I'll see if I can give that a shot once I get the time. If it works, we can contact the extension maintainer(s) after that.

**Comment by TheTripleV** [comment]
If there are concerns about the pip version of sphinxext-rediraffe, you may consider pinning it's version. Additionally, it is also available through conda.

**Comment by FroggyFlox** [comment]
@phillxnet, small "detail" question: 
What would you prefer with regards to indentation for our `.rst` files?

As of now, we have a mix of 2, 3 spaces (so far, at least). As I'm reorganizing a lot of files, I figured I might as well take care of that too (in its own separate commit as we do for `black` in rockstor-core).

**Comment by phillxnet** [comment]
@FroggyFlox Re spaces I would go for 2 spaces for our 'unit'. It's like we use in the html of our code repos. The sets of 3 were not intended by me but our docs have now many contributors and quite the vintage. But it's your call if you are to set about it.

So in short I vote for 2 spaces, but go with what you think and I'm happy to go with your decision on that going forward.

**Comment by FroggyFlox** [comment]
Thanks for the input, @phillxnet; I personally see 3 spaces as rather odd so I'm OK to go with 2 spaces throughout.

I now have moved everything around to get a cleaner top-level tree:
![image](https://user-images.githubusercontent.com/30297881/126078557-f90eea79-1c75-4d20-8fdf-b72f98a90bf0.png)

I do need to fight/figure out the left navbar menu (made by `fulltoc`) as it's not the way I would like it to be, but I think we're getting there!

**Comment by phillxnet** [comment]
@FroggyFlox Nice.

**Comment by FroggyFlox** [comment]
@phillxnet ,

I've noticed that some of the images we have in the repo are no longer used, for instance:

- cli.png
- clone_share.gif

As these seem to be older files, I suppose they have been replaced by newer ones or simply deprecated. Would you prefer us to keep them around or simply delete them from the repo?

**Comment by phillxnet** [comment]
@FroggyFlox Re:
> Would you prefer us to keep them around or simply delete them from the repo?

I say we delete them. If they turn out to be of interest in the future we can always retrieve them from an earlier git checkout.
Nice find. Thanks.

**Comment by FroggyFlox** [comment]
> We might also re-consider the method/mechanism by which we generate this table of contents / top navigation page within the docs: sphinxcontrib-fulltoc.

I think I now have a working solution for the TOC that does **not** require the `sphinxcontrib-fulltoc` extension. See below for an illustration.

![image](https://user-images.githubusercontent.com/30297881/126868158-8a33d853-1087-4fb8-bfb9-78b578c851d7.png)

**Comment by FroggyFlox** [comment]
As can be seen in 5c266f5, I gave `rediraffe` a real-world test and learned something important: one needs to write the redirections before making any change to the files. Luckily, rediraffe has an option to deal with that so I could still use it to detect all changes in files and create redirections for it; all files except ~3 that weren't detected but still listed as needing to be manually updated so that's no big deal. 
This is definitely a very helpful extension to have here.
