### ISSUE TITLE
Mixed HTTP and HTTPS content blocked prevents loading of font

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#285]
When loading any page, I noticed a discrepancy in font used between the production server (rockstor.com/docs) and a local server (using `python -m http.server`).

The Firefox web developer tool reports:
```
Blocked loading mixed active content “http://use.edgefonts.net/source-sans-pro.js”
```

The Vivaldi (Chrome) web developper tool reports:
```
Mixed Content: The page at 'https://rockstor.com/docs/' was loaded over HTTPS, but requested an insecure script 'http://use.edgefonts.net/source-sans-pro.js'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by FroggyFlox** [comment]
@phillxnet , while `http://use.edgefonts.net/source-sans-pro.js` seems to be a valid solution, I wonder if we actually need that remote call to this script. I'll try to see if I can figure out why we need it and what are our alternatives as I feel it would be better *not* to rely on a remote script like that.

**Comment by FroggyFlox** [comment]
This is a novel area for me so I had to go back to basics ;-).

EdgeFonts is a web font provider by Adobe, and is now [Adobe Fonts](https://fonts.adobe.com/). This one unfortunately now requires a subscription, it seems. According to Mozilla's documentation on web fonts, they do refer to Google Fonts as being the only one not requiring a subscription and remaining free (emphasis mine):

> Online font services generally store and serve fonts for you, so you don't have to worry about writing the `@font-face` code, and generally just need to insert a simple line or two of code into your site to make everything work. Examples include Adobe Fonts and Cloud.typography. **Most of these services are subscription-based, with the notable exception of Google Fonts, a useful free service**, especially for rapid testing work and writing demos.

[https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts#using_an_online_font_service](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Web_fonts#using_an_online_font_service)

We may thus either:
- use `https://use.edgefonts.net/source-sans-pro.js`
- switch to the Google Font service, which would mean replacing our current `http://use.edgefonts.net/source-sans-pro.js` with either:
```html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet"> 
```
or:
```html
<style>
@import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap');
</style> 
```

**Comment by phillxnet** [comment]
@FroggyFlox Nice find. Much like the one I addressed recently on the website:

https://github.com/rockstor/rockstor-website/pull/13

Where I simply removed the googleapis import in our css (http that time) as we seemed to be fine without it entirely. There was an https as you have suggested but I keen to not have google references if we can help it.

And given the call fails with our online / production variant anyway, but as far as I know we still render OK. Maybe we just, as per the website, remove these imports/references all together and presumably leave the browser to wing-it with built-in or system fonts.

How does that sound to your? The fewer connections we have to make just to show the local content the better I think.

**Comment by FroggyFlox** [comment]
> How does that sound to your? The fewer connections we have to make just to show the local content the better I think.

Agreed, we do not _need_ to use an external font like `source sans pro`. We currently have the following:
```css
body { 
  font-family: source-sans-pro, sans-serif;
  font-size: 16px;
  line-height: 1.5em; 
}

h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4 {
  font-family: source-sans-pro, sans-serif;
  font-weight: normal;
  color: #333;
}
```
... which uses `sans-serif` as alternative if `source-sans-pro` cannot be found, explaining why we're rendering ok. It's not as neat as `source-sans-pro` in my opinion, but I would see it as a detail. This is just my opinion, though.

To summarize, I agree that we can "simply" remove that external call. According to the Mozilla's documentation linked above, it seems we could "host" `source-sans-pro` on our server and use it locally, but that might be something to explore in a later PR.
