### ISSUE TITLE
Styles for admonitions are not defined

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#288]
Some of the Sphinx directives that we used, such as `.. note::` and `.. warning::` are not defined in our CSS stylesheets and thus result in "bare" text without proper style applied to it. See below for an example of a `.. note::` directive:
![image](https://user-images.githubusercontent.com/30297881/126836642-68755109-6921-4f23-85e6-646e55929f78.png)

To get appropriate style, we currently have to use a `.. raw:: html` block with the bootstrap.js styles of `alert alert-info`, for instance. This yields:
![image](https://user-images.githubusercontent.com/30297881/126836997-30cacd73-6562-45c6-9d0f-e8a27a122485.png)

While this works, we loose the advantage and simplicity of using pure restructuredText and its internal linking, etc... for the content of these `.. raw:: html` blocks. As illustrated in https://github.com/rockstor/rockstor-doc/issues/283#issuecomment-875157889, for instance, we are "forced" to use external links to ourselves as a result.

## Proposition  
To remedy this, it is proposed to use our stylesheets to define a proper style for such admonitions. Note that we can simply copy the same CSS bits of the bootstrap.js styling we use to get identical results as the currently used `.. raw:: html` blocks.

**Comment by FroggyFlox** [comment]
@phillxnet, if you agree with this proposition, I already have a few bits written related to that while working on #284 so feel free to assign me to this issue if you'd like.

**Comment by phillxnet** [comment]
@FroggyFlox Yet another nice find. Well done. Assigning gladly as requested.
Thanks.
