### ISSUE TITLE
Search results don't display matched contents

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#289]
A search will correctly list the page(s) with a result, but the matched contents will not be displayed. For instance, note the three dots in the screenshot below:
![image](https://user-images.githubusercontent.com/30297881/126869504-5f563ff3-8e2d-4976-b501-9b4eee4180ba.png)

The developer console explains what happens:
```
Content block not found. Sphinx search tries to obtain it via '[role=main]'. Could you check your theme or template.
```
from:
```js
  htmlToText : function(htmlString) {
      var htmlElement = document.createElement('span');
      htmlElement.innerHTML = htmlString;
      $(htmlElement).find('.headerlink').remove();
      docContent = $(htmlElement).find('[role=main]')[0];
      if(docContent === undefined) {
          console.warn("Content block not found. Sphinx search tries to obtain it " +
                       "via '[role=main]'. Could you check your theme or template.");
          return "";
      }
      return docContent.textContent || docContent.innerText;
  },
```

We can thus see that we're missing this `role=main` component. A quick search online explains it is actually the case for some custom themes that haven't been updated (as ours), and provides further explanations:
https://github.com/sphinx-doc/sphinx/pull/7192#issue-378500099https://github.com/sphinx-doc/sphinx/pull/7192#issue-378500099

It seems to be easily fixable by adding this required role, like it was done in the sphinx theme below:
https://github.com/f5devcentral/f5-sphinx-theme/pull/126/files

I quickly tested that fix above and could indeed get the full results back:
![image](https://user-images.githubusercontent.com/30297881/126869709-2d19ff68-0a37-452d-b878-dec2bd0f1645.png)

**Comment by phillxnet** [comment]
@FroggyFlox Fancy that. Well done.

Apologies for missing this myself. And thanks for the contextual links.
