### ISSUE TITLE
Indicate no auto update option in Rockstor 4 Web-UI

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#293]
Currently we have no auto update option intergrated into our Web-UI for Rockstor 4. Indicate this within the following post #290 pr merge section:
docs/interface/system/update_channels.html#auto-updates

A link or section explaining the yast2 alternative might be good here. I.e. packages required and how to invoke this capability via ncurses yast2 interface.

**Comment by FroggyFlox** [comment]
Linking to #270 as it is a similar issue that would most likely be also fixed by fixing the current one.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
Closing as
Duplicate of #270
