### ISSUE TITLE
Update "Developers" section re recent build changes

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#319]
Due to a change/update in authentication mechanism re pypi we have had to alter our build procedure a little. Mainly due to our use of a now outdated python 2 based build system. See: https://github.com/rockstor/rockstor-core/issues/1877

Previously we setup and executed our source build by:
```
bootstrap.py -c buildout.cfg
buildout -N -c buildout.cfg
```

This was affected by staggered brown outages intended to inform those using older build systems such as ours that changes were afoot. These changes have now become permanent and represent a deprecation of non-SNI compatible clients. 

Update our doc entries to reflect the work around we are now using:

```
zypper --non-interactive install python2-pip
pip2 install zc.buildout
buildout bootstrap
```
Thanks to @FroggyFlox for researching the origin of these difficulties and presenting the above work around. Much appreciated.

Apologies for the delay in establishing this issue.

## Components:
- [x] Move to suggesting the use of a v4 install instance. Contributors should be familiar with this install and it has many of the rpm's dependencies and little else so is a good start.
- [x] add install command for required developer dependencies- Build VM  section in contribute page.
- [x] Fix above detailed build command chanages.
- [x] Be opinionated about the build directory, there's no harm and it's a quicker read.
- [x] Remove dead YouTube link in this section.
- [x] Remove some overly chatty bits in Local git repo setup section.
- [x] Remove adding name to authors file as we have now only 2 in there but 35 git contributors. It is suspected that this is due to the first 2 including an email. This also represents an overhead for those doing small patches.
- [x] Update /opt/rockstor-dev/var/log "ls -la" entry as we now have no ztask.log but a new entry or two for huey.
- [x] Add systemd services info.
- [x] Add updating info/context re rpm.
- [x] Move contribute.rst to [Semantic Liefeeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).

**Comment by FroggyFlox** [comment]
Thanks a lot, @phillxnet !
Note that from memory I believe we use `zc.sourcerelease` only for rpm building and is not needed for `buildout.cfg`.

**Comment by phillxnet** [comment]
@FroggyFlox Thanks, editing accordingly.

**Comment by phillxnet** [comment]
I am currently working in this issue.
