### ISSUE TITLE
Documentation for RockStor Raid levels

### ISSUE THREAD

**Issue by sujeetsr** [rockstor/rockstor-doc#32]
Update documentation with 
List of raid levels that can be used while creating a pool
description of each
min no of drives

**Comment by phillxnet** [comment]
@schakrava I believe this one has now been addressed by yourself in the following commit:-
https://github.com/rockstor/rockstor-doc/commit/65d89015aa744730874ae6f96838913d9f8b2a22

**Comment by schakrava** [comment]
Sounds good to me. Thanks @phillxnet !
