### ISSUE TITLE
Add running tests to developer contribution section

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#322]
Although we now have a fully update source build and basic functional test guide in contribute.rst via now merged:
#321 
We do not have any mention or guide on running our build-in unit tests.

It is proposed that we add a testing section to our "Build VM initial setup"  so that we have a new 3. entry:

1. configure
2. build
3. test

And move the existing text concerning manual testing into this proposed 3rd section. And add to it info on our existing tests and how to run them:
```
cd /opt/rockstor-dev/
./bin/test -v 2

Ran 216 tests in 17.094s

FAILED (errors=1)
```
(See https://github.com/rockstor/rockstor-core/issues/2327 for our current single test error)

**Comment by FroggyFlox** [comment]
Excellent idea, I didn't even notice we didn't have that already.
