### ISSUE TITLE
Home Nas Guide How-to has redundant/misleading info

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#342]
Thanks to forum member Mike-B for point out our now very old and possibly redundant "Home Nas Guide" error re client access:

> Using Rockstor
> 
> Accessing a shared folder from a Mac client
> 
> To access a shared folder on Rockstor from a Mac, you have to create a pool, create a share in the pool, and export it using Samba. This is explained in the Creating a share section.
> 
> Once you have exported the Share using Samba on Rockstor, it should appear as a folder in the Devices menu on your Mac.
> 
> Accessing a shared drive from a Windows client
> 
> To access a shared folder on Rockstor from a Mac, you have to create a pool, create a share in the pool, and export it using Samba. This is explained in the Creating a share section.
> 
> Once you have exported the Share using Samba on Rockstor, it should appear as a folder in the Devices menu on your Mac.

Mike points out that we have an abundance of "Mac" mentions here !

We might do better without this How-to or to edit it appropriately and likely reference our now existing centralised guides on client access.

Forum reference:
https://forum.rockstor.com/t/importing-loading-files-from-usb-fat-structured/8132/6

**Comment by phillxnet** [comment]
@FroggyFlox Re:

> I would tend to favor removing this guide, personally:

Agreed. But could we pop in one of those magic redirect things as I've seen links to this howto on the interwebs. We could just redirect to our top doc page or the like.

**Comment by FroggyFlox** [comment]
> But could we pop in one of those magic redirect things as I've seen links to this howto on the interwebs. We could just redirect to our top doc page or the like.

Good idea! I think the top doc page (rockstor.com/docs) would be the best candidate as that How-to aimed at covering pretty much everything that is in the docs, actually.
