### ISSUE TITLE
IP address-based access format for windows is incorrect in file sharing documentation

### ISSUE THREAD

**Issue by Hooverdan96** [rockstor/rockstor-doc#343]
In the documentation here:
https://rockstor.com/docs/interface/storage/file_sharing/samba_ops.html#how-to-access-a-share

The ip based access needs to contain 2 leading backslashes instead of the single one depicted in the documentation.
So, it should be `\\192.168.1.21` instead.

Reference to forum thread:
https://forum.rockstor.com/t/importing-loading-files-from-usb-fat-structured/8132/10?u=hooverdan

**Comment by FroggyFlox** [comment]
This issue will probably be fixed by the same PR that will be submitted to fix #110. See comment below for further details:
https://github.com/rockstor/rockstor-doc/issues/110#issuecomment-932333333
