### ISSUE TITLE
Add section on installing Kernel_stable_Backport and filesystem repos to enhance raid levels

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#344]
Our current upstream has provisioned the parity raid levels as unsupported, rendering the btrfs raid 5/6 pool options as read only. If we simply enable rw access, via a kernel or the like, we are second guessing upstream and deviating in the process. It is proposed that we instead add documentation on how to install the OBS supplied Kernel_stable_Backport repo and the filesystems repo. This way we are simultaneously updating the kernel to the upstream Stable version where this provision is not in place. There-by also providing for folks who want to experiment with for example btrfs data raid6  metadata raid1c4 to allow for 2 disk failure.

A proviso should be included to indicate that this is a deviation from our 'set' upstream and as such may involve support difficulties due to the custom nature of the resulting install. But that it is a way to achieve a rw parity raid setup until such time as our upstream no longer disables write access for the parity raids in it's default kernels.

**Comment by phillxnet** [comment]
I am currently working on this issue.

**Comment by phillxnet** [comment]
It looks like the most appropriate place to locate this guide is in the How-to section:

"Installing the Stable Backport kernel"
Reference: https://build.opensuse.org/project/show/Kernel:stable:Backport

**Comment by FroggyFlox** [comment]
Agreed... Maybe we could link to it in a future PR from the "raid" section (Pools) when addressing the raid 5/6 situation.

**Comment by phillxnet** [comment]
> Agreed... Maybe we could link to it in a future PR from the "raid" section (Pools) when addressing the raid 5/6 situation.

Agreed. I'll pop that in as I've had to add a target link (pool balance) to that page anyway. Plus if we hide this away in a how-to it may never be found by those wondering why their new parity raids are read-only.

**Comment by phillxnet** [comment]
@FroggyFlox I've done the following so far:

![warning-re-56](https://user-images.githubusercontent.com/2521585/146602893-eaf8a862-6fb0-413a-88b6-5198896b4240.png)

Should have a pr for this issue done shortly.

**Comment by FroggyFlox** [comment]
Looks great!
