### ISSUE TITLE
Md raid not supported under btrfs

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#355]
Thanks to forum member g6094199 for highlighting this shortfall in our Minimum System Requirements recomendations re raid under btrfs.

We have:

> Hardware raid underneath btrfs, Rockstor’s chosen filesystem, will weaken data integrity assurances.

This should likely also include md raid which is an alternative software raid that pre-dates btrfs and is likewise not recommended and will similarly weaken data integrity.

Suggested fix:

> Hardware raid, or md/dm software raid, underneath btrfs, Rockstor’s chosen filesystem, will weaken data integrity assurances.

We should also indicate that md/dm software raid is not supported as we have likely a pretty buggy response to drive management in that case. Likely even broken on non system disks which is where we experimentally introduced at least partial reporting of such; without any further ability to control this. And our current v4 installer has no capability in this area: intentionally.

Forum thread reference:
https://forum.rockstor.com/t/disk-scan-error-on-dev-sde/8185

**Comment by g6094199** [comment]
plz keep in mind that MD raid is still the preferred raid solution in OMV and not supporting MD would hold people back from migrating from OMV to Rockstor.

**Comment by phillxnet** [comment]
@g6094199 There is always the option to migrate data to our preferred raid arrangement.
Supporting mdraid would be counter to our prime directive of data integrity as that is not a guarantee of mdraid, but it is one for btrfs. Hence this issue extending our hardware raid advice to mdraid. It is akin to hardware raid or the half-way of dm raid in that it does not know which copy of a 'thing' is the correct one. And so cannot self heal in an informed fashion.

We did have limited mdraid raid awareness in our older CentOS guise but that was only for he system drive and only in a very limited fashion. We are strictly btrfs only on the filesystem and raid front. However given our generic linux underpinning folks can easily mount mdraid (included in our installer) and migrate that data to Rockstor created btrfs volumes (Pools) and subvolumes (shares).

Apologies but I failed to link back to you forum thread that lead to this issue's creation. I'll edit the original issue text to sort that.

In short we will not be adding mdraid to our capabilities, hence this doc update. This is due to it's inability to do as btrfs does and know the truth of the data it protects. It is akin to a straight copy of hardware raid but in software. Btrfs is more than that. We also value the comparative simplicity that is synonymous with sticking to a narrow set of technologies. I.e. we support only btrfs raid.

An option for you to migrate your in-place mdraid array without using any more disks would be technically challenging but not impossible. It might make for a nice How-to around degrading and existing md to re-deploy it's prior members into a btrfs managed pool. But that would be a way dodgy / risky move and I'm not sure how many takers there would be. If a backup is available that is another option. But two backups would be the preferred. Always tricky migrating data, especially from an older format. But in this case it's unavoidable given our stance. But a command line mount of an md raid is entirely possible and could then be used to migrate to a new pool. But that inevitably involves more disks. Keep in mind thought that unlike mdraid btrfs can modify it's underlying raid level on-the-fly. So you could start out with a single disk pool (btrfs raid single), move data to that disk, then add a disk to that pool and simultaneously move it to btrfs raid1. The disks don't have to be the same size but similar sizes would make sense.
