### ISSUE TITLE
Functions to configure commonly-used settings - Set Static IP, Configure Proxy, Open-VM-Tools

### ISSUE THREAD

**Issue by eric-marcus-mbu** [rockstor/rockstor-doc#358]
- It would be very convenient to have the ability to set a static ip address as part of the installation. Installs are often started without a connection to a dhcp network.
- It would be very useful to have the ability to set and enable a proxy for internet access when on a private ip network.  Otherwise, installation of updates, Rock-Ons, etc is not possible. I envision this as a button on the Services page.
- VMware is a common hosting platform to install Rockstor and the Open-VM-Tools package can enable increased management function.  It would be very convenient to simplify installation of this package, either as part of the installation or from the GUI after installation.

**Comment by phillxnet** [comment]
@eric-marcus-mbu Thanks for creating this doc issue; all good points well worth adding.

There may be spin off rockstor-core issues here also but initially all these can be addressed here in docs initially irrespective of future Web-UI options.

We can't do static ip setup via kiwi-ng, the system that makes our installer (https://github.com/rockstor/rockstor-installer) and I'm super keen to keep the install as simple as possible for the vast majority of users. But I agree a small doc entry for this should do it, especially as it's a single line mncli command that we can present in the docs for the more advanced users who need this.

VMware is common but I'm not keen on including it as default but we could add it as a remarked out option in our installer config to ease the path for those wanting to create custom installers so it's there from the get go. I've created the following issue in our DIY instaler repo for this:

https://github.com/rockstor/rockstor-installer/issues/95

I'm also not keen on having this options clutter the Web-UI and carrying the consequent code as it's only a single line command used by those likely already totally happy with that resource but as always it may end up getting traction and ending up with someone adding it in the Web-UI. We do intent to open up more advanced features as we go and this may well be one such element within an advanced tab/tick somewhere.

Thanks for kicking off some nice suggestions here. If you end up having a go at this issue then make sure you pop in a comment indicating this to avoid duplication of effort.
