### ISSUE TITLE
Fix and update links re open source zoneminder app zmNinja

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#365]
The referenced desktop and mobile apps for zoneminder post 1.30 referenced in our docs has had a maintainer change and this has lead to a broken link as the prior maintainer, who was no longer able to sustain support time requirements, has passed their code over to the  upstream zoneminder team.

Creating separate issue here as this needs more than just a URL fix or two.

See the new GitHub repo in Zoneminders own GitHub repo area now at:
https://github.com/ZoneMinder/zmNinja

And the initial zoneminder forum post that initiated this maintainer move:
https://forums.zoneminder.com/viewtopic.php?f=33&t=30996&p=122445#p122445

**Comment by Hooverdan96** [comment]
This pull request fixed #356 not 365, correct?

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks Re:

> This pull request fixed #356 not 365, correct?

This is the issue #365 that is closed by the pr #368. However you are right that this issue is a duplicate of an earlier #356.
So pr #365 fixes both in fact.
I'll make the notes accordingly.
Cheers.

Duplicate of #356
