### ISSUE TITLE
Update MinIO documentation to reflect new installation procedure from rockon-registry #302

### ISSUE THREAD

**Issue by MikeMcPherson** [rockstor/rockstor-doc#366]

**Comment by MikeMcPherson** [comment]
Whoops, I made a mistake in the documentation.  It's now fixed.

**Comment by phillxnet** [comment]
@MikeMcPherson Cheers. My apologies for not noticing earlier. I've yet to look at the Rock-on itself so hopefully this will all fall into place as intended.
