### ISSUE TITLE
Broken link to GitHub within contribute_documentation.rst

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#371]
We have a recent broken link shown up by our link checker, thank to @FroggyFlox for that work and it's subsequent GitHub actions integration.
```
(contribute/contribute: line   55) broken    https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests - 403 Client Error: Forbidden for url: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
...
(contribute/contribute_documentation: line  305) broken    https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue - 403 Client Error: Forbidden for url: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
```

**Comment by FroggyFlox** [comment]
@phillxnet ... I noticed a second link to the GitHub docs was failing in the same way (connection refused, I believe), but works when copied and tested manually in a browser... Maybe it's specific to being run inside the GitHub action worker?

**Comment by phillxnet** [comment]
@FroggyFlox Cheers. That is a concern. But I see this failure from my own running of the link test locally. But it still stands that they may be looking at browser signatures or the like. And failing this type of check.

We may have to remove those links in which case. I've updated the issue text accordingly.

**Comment by FroggyFlox** [comment]
Interesting that you see it from a local run too... They may be checking curl requests of that sort, then.

**Comment by FroggyFlox** [comment]
@phillxnet, I now see these two lines as `OK`:
```
(contribute/contribute: line   55) redirect  https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests - permanently to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
(contribute/contribute_documentation: line  305) ok        https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
```

It thus seems that issue resolved itself so I'll close it now... Feel free to re-open if you see otherwise.
