### ISSUE TITLE
add note to check ownership of shares post import

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#376]
Thanks to forum member parth for highlighting this issue. Imported pools can end up with root:root ownership on previously edited user/group shares (subvols). It is propose we add a note to this end to inform users to expect and check for this outcome.

Relates to the following major doc section:
https://rockstor.com/docs/interface/storage/disks.html#import-btrfs-pool

Form thread reference:
https://forum.rockstor.com/t/solved-btrfs-subvolume-create-delete-fail/3943/11

We may also have a bug here regarding restoring but for now a doc entry would be a good heads up.

**Comment by phillxnet** [comment]
We do now have a related and recently added section regarding user / group changes from our v3 in:
'Migrating from Legacy V3 to V4 “Built on openSUSE”'
under:
'Users and default group' https://rockstor.com/docs/howtos/v3_to_v4.html#users-and-default-group

Noting here for additional context that we might like to link too while addressing this issue.

**Comment by Hooverdan96** [comment]
Adding another related reference/occurrence recently observed on 4.5.9-1 by [@jihiggs](https://forum.rockstor.com/u/jihiggs)

https://forum.rockstor.com/t/file-permissions/8813/
