### ISSUE TITLE
Incorrect "maintainer" listed in Docker image

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#384]
As seen in the [description](https://github.com/rockstor/rockstor-doc/pkgs/container/rockstor-doc/7887506?tag=master) of our Docker image for building our docs, we are currently listing the "Sphinx Team" as maintainer of the image:
```json
 "labels": {
    "maintainer": "Sphinx Team <https://www.sphinx-doc.org/>",
  }
```

While this is a minor issue, it isn't proper to list the Sphinx Team as maintainer of our image; this label most likely originates from our base image (the official one).

We should thus specify the following in our image:
```dockerfile
LABEL org.opencontainers.image.authors="Rockstor Team <https://rockstor.com>"
```

**Comment by phillxnet** [comment]
@FroggyFlox Nice find. Re:

> @phillxnet , if you're OK with this change, which URL would you prefer?

B for sure. www is now very dated and an unused subdomain.

> Regarding the name, would you prefer "Rockstor Team", or "Rockstor inc."?

"Rockstor Team" as it's the team contributing/authoring this. Or preferred and to be consistent with our signing keys and 'about us' web page "The Rockstor Project".

Cheers.

**Comment by FroggyFlox** [comment]
Thanks for the feedback!
I'll go with:
"The Rockstor Project \<https://rockstor.com>"
