### ISSUE TITLE
Gunicorn HTTP server hogging CPU

### ISSUE THREAD

**Issue by cron410** [rockstor/rockstor-doc#39]
Version 3.6-9. I am running a VM in ESXi with 1 vCore of CPU and 2gb of ram. This is obviously for testing purposes. Gunicorn seems to be hogging the most CPU out of all processes. It never dips below 20% usage and is continually over 40% usage. I got these numbers with TOP on the CLI. This is the only command I have run on the CLI so far.

Here is my dashboard in case the graphs and statistics are somehow causing HTTP server CPU hogging. 
![image](https://cloud.githubusercontent.com/assets/3082899/6680807/8856240e-cc32-11e4-944d-8204791abecb.png)

**Comment by cron410** [comment]
![image](https://cloud.githubusercontent.com/assets/3082899/6680817/ac0a486c-cc32-11e4-9a36-72630a1be759.png)

**Comment by cron410** [comment]
Did a fresh install with the 3.5 iso. CPU usage is still high, but TOP seems to be missing some info now.
![image](https://cloud.githubusercontent.com/assets/3082899/6701128/cb49330c-ccee-11e4-82fe-43591fe6d0b0.png)
![image](https://cloud.githubusercontent.com/assets/3082899/6701140/fc710f4a-ccee-11e4-95f2-35c437b9b49a.png)

**Comment by phillxnet** [comment]
@cron410 could you try the recently released 3.8-2 as in the interim there have been many improvement.  Thanks for all the detail and pics.

**Comment by cron410** [comment]
Still seeing issues with gunicorn and dc2 processes. Now running on a beefier server Dell R300 with a  quadcore Xeon 2.33GHz CPU and 12GB ram running ESXi 5.5 on a raid 5 array. The CPU graph in Rockstor web interface also seems to have the wrong scale.
![image](https://cloud.githubusercontent.com/assets/3082899/9144934/89a82be2-3d1e-11e5-8b24-f392b4c99ecc.png)
![image](https://cloud.githubusercontent.com/assets/3082899/9144936/9ad7ed6c-3d1e-11e5-8be1-98c569c18539.png)
![image](https://cloud.githubusercontent.com/assets/3082899/9144938/a00c8aea-3d1e-11e5-9118-a348c3a88fd4.png)
![image](https://cloud.githubusercontent.com/assets/3082899/9144963/be539610-3d1e-11e5-990d-ac70a8502953.png)

**Comment by cron410** [comment]
I am running the latest 3.8-4 for your reference. Kernel: 4.1.0-1.el7.elrepo.x86_64

**Comment by phillxnet** [comment]
@cron410 Thanks for the details and update. The cpu use does look to be uncommonly high. My first guess is that you have minimal actual cpu allocated to the Rockstor instance within the ESX, ie with only a low power single core cpu allocated then Rockstor would use a high percentage of it's cpu time.  I'm afraid I am almost completely unfamiliar with ESXi but presumably there is a facility to specify the cpu resources to allocate to the Rockstor instance as it currently is showing only one core.
```
Could you post the results of:-
cat /proc/cpuinfo
```
so we can see what cpu spec the Rockstor instance believes it is on.
Also from the last graph you post it looks like the cpu Mhz goes all they way down to 23/24MHz so the high cpu usage may in some instances be showing percentage of use for the cpu at it current (potentially very low) MHz capacity; until that capacity is increased by the cpu stepping up speed.

So to me this currently looks like an artefact of the virtualization. Note also that Rockstor is not actually that light a system at the moment, especially with the monitoring enabled. There is however continued work on improving efficiency. But yes your instances does seem cpu high. Lets see what cpuinfo gives out and if you could experiment with cpu allocation in ESXi that might tell us something.

Thanks.

**Comment by cron410** [comment]
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           L5410  @ 2.33GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 2333.333
cache size      : 6144 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc aperfmperf pni ssse3 cx16 sse4_1 xsave hypervisor lahf_lm dtherm
bugs            :
bogomips        : 4666.66
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:


here is a screenshot of cpu time for dc2 after running all weekend
![image](https://cloud.githubusercontent.com/assets/3082899/9176903/f4ac852a-3f5b-11e5-8553-2a2b47348b68.png)

**Comment by cron410** [comment]
Change the CPU config to 2 cores and left the server running overnight. The usage is much better, although I have not logged into the web interface. Ill do that now, and close it like I did before the weekend and see what happens overnight. Here is my current TOP.
![image](https://cloud.githubusercontent.com/assets/3082899/9210171/b78685ae-4048-11e5-8c51-4b1879e3f3f6.png)

**Comment by cron410** [comment]
After logging into the web interface, here are my stats as reported by Rockstor. 
![image](https://cloud.githubusercontent.com/assets/3082899/9210253/2cececfc-4049-11e5-9b74-5ce3c40cc505.png)

and here is what TOP is reporting.
![image](https://cloud.githubusercontent.com/assets/3082899/9210294/6b4761a8-4049-11e5-8733-2492d6c8c0c6.png)

I'll let it sit overnight and report back.

**Comment by schakrava** [comment]
Thanks for providing details @cron410 , really appreciate the help to improve Rockstor. Note that dc2 and data-collector are being consolidated as we speak and we are making things light weight. Most fixes if not all should go into 3.8-5, FYI.

**Comment by cron410** [comment]
Awesome. I have auto update enabled.

**Comment by cron410** [comment]
This has been completely resolved in 3.8-8
