### ISSUE TITLE
Add missing settings env in code testing

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#414]
In the following section https://rockstor.com/docs/contribute/contribute.html#code-test we have a missing:

> export DJANGO_SETTINGS_MODULE=settings

line. Not a problem if folks have already set this previously while following another of the developer sections, but it would be nice to have this in for completeness and to avoid folks running the tests as the first thing they try, and having an issue regarding not settings having been defined. This way each section can stand alone and there is not harm in re-defining repeatedly.

**Comment by FroggyFlox** [comment]
Sorry about missing that one, @phillxnet, I should have paid more attentiont :-\

**Comment by FroggyFlox** [comment]
@phillxnet ,
Once we move to poetry 1.2.0+, we might want to have a look at: https://github.com/mpeteuil/poetry-dotenv-plugin.
That plugin seems to have emerged from https://github.com/python-poetry/poetry/issues/337.

**Comment by phillxnet** [comment]
@FroggyFlox Cheers, that's nice. And I totally agree. The more self contained we can get the better.
