### ISSUE TITLE
Add how-to for RPM install on Leap base method

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#421]
This issue stems from a conversation with @phillxnet on the rockstor-website repo: https://github.com/rockstor/rockstor-website/pull/61#issuecomment-1460494019

We indeed currently have instructions for how to install Rockstor using its rpm on a Leap base install. These should *at least* also be present in our docs as a how-to. We could thus use this how-to in our docs as a single point of reference and point to these instructions wherever is needed (such as in our website downloads page, for instance).

**Comment by FroggyFlox** [comment]
A brief note on the following point (from ):

> we do have easy update capability here and potentially machined updatable as the copy-paste instructions are partially informed by the front-matter of that page:
> See the rpm_version entry for example here:
> https://github.com/rockstor/rockstor-website/blob/master/content/dls/rpm.md

We can do something very similar in Sphinx; I have actually wondered about a worthwhile use for it for a while so it seems like an interesting opportunity. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#substitutions for a starting point.

**Comment by phillxnet** [comment]
@FroggyFlox Re:

> We can do something very similar in Sphinx;

OK, so that looks promising. We could well use this type of thing in the docs.

**Comment by FroggyFlox** [comment]
> OK, so that looks promising. We could well use this type of thing in the docs.

I'll create a new issue for that, then.
