### ISSUE TITLE
Update links to now archived btrfs.wiki.kernel.org

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#424]
The Btrfs wiki that used to be hosted at btrfs.wiki.kernel.org now redirects to an archive version at https://archive.kernel.org/oldwiki/btrfs.wiki.kernel.org/index.php/Main_Page.html

As we can see on that page this content is no longer updated and thus considered **obsolete**.

Contents have been/are in the process of being migrated to https://btrfs.readthedocs.io/. We should thus update (when possible) the current links pointing to the now archived wiki to the new one at readthedocs.io.

**Comment by FroggyFlox** [comment]
We currently have:

| file | current link | proposed new target|
| ---- | ---- | ---- |
| data_loss.rst | https://btrfs.wiki.kernel.org/index.php/Glossary | https://btrfs.readthedocs.io/en/latest/Glossary.html |
| data_loss.rst | https://btrfs.wiki.kernel.org/index.php/SysadminGuide | no clear target identified |
| data_loss.rst | https://btrfs.wiki.kernel.org/index.php/Status | no clear target identified |
| data_loss.rst | https://btrfs.wiki.kernel.org/index.php/Btrfs_mailing_list | no clear target identified |
| faq.rst | https://btrfs.wiki.kernel.org/index.php/Main_Page | https://btrfs.readthedocs.io/en/latest/index.html |

There are 3 links without clear identical targets in the "new docs"... these should be investigated further before replacing them. For now, the redirect is still ~OK, although the information will soon be out-of-date for some.

**Comment by Hooverdan96** [comment]
With #447 some of the links have now find a new home.

<html>
<body>


file | current link | proposed new target
-- | -- | --
data_loss.rst | https://btrfs.wiki.kernel.org/index.php/Glossary | https://btrfs.readthedocs.io/en/latest/Glossary.html
data_loss.rst | https://btrfs.wiki.kernel.org/index.php/SysadminGuide | https://btrfs.readthedocs.io/en/latest/dev/dev-btrfs-design.html
data_loss.rst | https://btrfs.wiki.kernel.org/index.php/Status | https://btrfs.readthedocs.io/en/latest/Status.html
data_loss.rst | https://btrfs.wiki.kernel.org/index.php/Btrfs_mailing_list | no clear target identified
faq.rst | https://btrfs.wiki.kernel.org/index.php/Main_Page | https://btrfs.readthedocs.io/en/latest/index.html


</body>
</html>

The btrfs mailing list could just be replaced with the link to here:
http://vger.kernel.org/vger-lists.html#linux-btrfs

**Comment by Hooverdan96** [comment]
@FroggyFlox, with all of the links now dispositioned including the mailing list one, I think this issue can now be closed.

**Comment by FroggyFlox** [comment]
Thanks a lot for all that work, @Hooverdan96!
Closing as requested, as fixed by #447.
