### ISSUE TITLE
Improve Quick-Start and FAQ visibility and clarity

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#425]
Although we do have a Quick-Start page, it cannot be readily found on the home page and one has to look for it to find it. Moreover, its content lacks a concise summary of simple steps to get you up and running with Rockstor.

It would help the first user experience to better highlight our Quick-Start instructions and guide the user to it.
Similarly, we could try to better highlight our FAQ page, which is potentially even more important for a first time user seeking brief answers.

**Comment by phillxnet** [comment]
@FroggyFlox Re:
Agreed.

> Similarly, we could try to better highlight our FAQ page, which is potentially even more important for a first time user seeking brief answers.

We do link to our FAQ from the main website however.
