### ISSUE TITLE
PBP guide has broken dban link

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#438]
A recent build for pr #437 resulted in the following link check failure:
"(installation/pre-install-howto: line   80) broken    https://dban.org/ "
Creating this issue accordingly.

**Comment by Hooverdan96** [comment]
Maybe point to the successor of dban that uses nwipe. Since it was a fork, look and feel is pretty similar. Also, seems to be in active development and deals better with newer BIOS implementations.

https://github.com/PartialVolume/shredos.x86_64

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks for this info: much appreciated. I was completely unfamiliar with both nwipe and ShredOS.
From their GitHub README.md at the link you provided we have:

> What are the advantages of nwipe over dwipe/DBAN? Well as everybody probably knows, DBAN development stopped in 2015 which means it has not received any further bug fixes or support for new hardware since that date. Nwipe originally was a fork of dwipe but has continued to have improvements and bug fixes and is now available in many Linux distros. ShredOS hopefully will always provide the latest nwipe on a up to date Linux kernel so it will support modern hardware.

So as you say this looks like an ideal drop-in replacement in our PBP.
Cheers.
