### ISSUE TITLE
Add Tailscale to list of features

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#461]
Our welcome page includes a table with a list of features offered by Rockstor.
Since Rockstor-5.0.5-0, we now also implement Tailscale so we should add this to the list.

@Hooverdan96, @phillxnet:
Assuming you are OK with adding Tailscale there, I'm wondering *where* to put it in that list. It seems the order of features in that list is based on what we would like to emphasize the most first, so I'm not sure where to put it exactly.

**Comment by Hooverdan96** [comment]
I don't think it matters all that much, but I would think it could go in between these two:

<img width="987" alt="image" src="https://github.com/rockstor/rockstor-doc/assets/35113775/389146d8-9a09-48b5-bb25-23eb4166f704">

Before the simple installation process.

**Comment by FroggyFlox** [comment]
Thanks, @Hooverdan96... I have to apologize as you made me realize I didn't include a reference link to specify the list to which I was referring... My apologies :(
I'm actually thinking about adding it to the following list:
https://rockstor.com/docs/#features

**Comment by Hooverdan96** [comment]
Ah, got it. Do make an initial suggestion I'd put it before or after the SSH entry:

<img width="598" alt="image" src="https://github.com/rockstor/rockstor-doc/assets/35113775/a2630123-cb79-4594-a044-4e65f6491b5a">

since it kind of aligns with the "ways to remotely connect"?

**Comment by FroggyFlox** [comment]
That makes sense; I like it!

**Comment by Hooverdan96** [comment]
Since you will already be in there, would it make sense to remove the version reference for these two?

<img width="571" alt="image" src="https://github.com/rockstor/rockstor-doc/assets/35113775/756e9d89-5250-44d0-8ddb-c4613d3ea7a6">

something like "Rockstor uses sssd"

since version 3 is already deprecated and we are even moving towards a 5.x version now

**Comment by FroggyFlox** [comment]
Good point; I'll include that as well, then.
