### ISSUE TITLE
Update "Install on Vanilla openSUSE/SuSE SLES" re OS versioning

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#463]
Our current Vanilla install instructions, linked from our Downloads page, pertains to 15.4 - given we have only a few weeks left before 15.4 is EOL, and as yet no installers on 15.5 - but testing rpms, it is proposed that we changes/test these instructions to pertain to 15.5 or both if that still works. This way we have a path for testers to jump on our mid testing phase rpms before we get to preparing new installers as we approach our next Release Candidate phase in current testing channel (likely 5.0.6/7 start).

https://rockstor.com/docs/howtos/rpm_install.html

**Comment by Hooverdan96** [comment]
just for documentation purposes, mainly the repo area would have to change to:
```
zypper --non-interactive addrepo --refresh -p105 https://download.opensuse.org/repositories/home:/rockstor/15.5/ home_rockstor
zypper --non-interactive addrepo --refresh -p97 https://download.opensuse.org/repositories/home:/rockstor:/branches:/Base:/System/15.5/ home_rockstor_branches_Base_System
rpm --import https://raw.githubusercontent.com/rockstor/rockstor-core/master/conf/ROCKSTOR-GPG-KEY
zypper addrepo -f http://updates.rockstor.com:8999/rockstor-testing/leap/15.5/ Rockstor-Testing
zypper --non-interactive --gpg-auto-import-keys refresh
```

and I'd recommend to add a comment to the last lines on installing and starting with something like "use the latest test release version tag which can be found on github" or something of the likes, so that as more test releases are created we don't have to update the page until the next Leap (or switch to TW or what have you) release.

**Comment by phillxnet** [comment]
@Hooverdan96 Thanks and I mostly agree. Except regarding:

> "use the latest test release version tag which can be found on github"

The intention was to guide folks towards the first stable release available, as that is always first available in the testing repo. And when we popped in that specific version it was latest RC at the time I believe. But yes, we do need something like what you suggest to age better.

Maybe:

> See our [GitHub Releases](https://github.com/rockstor/rockstor-core/releases) for version info; no version = latest testing: intended for development use only.

How about that?

**Comment by phillxnet** [comment]
We also need to add a Tailscale repo to the list here. As per:

https://github.com/rockstor/rockstor-installer/issues/142
