### ISSUE TITLE
plex-howto rock-on guide

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#47]
Given Plex is a very popular server software at least in the home NAS field a quick guide on installing via a Rock-on might be nice.  Especially given the Rock-on system is now coming along.

I am working on a pull request to this end.

**Comment by schakrava** [comment]
@gkadillak is planning to brush up the Rock-ons UI a little bit. The formatting, tooltips and flow is a bit error prone right now. We are planning to make it better in the current release cycle. I say we wait till that happens. Having said that, this document should get a lot of eye balls, just saying. no pressure :)

**Comment by phillxnet** [comment]
@schakrava OK, I'll sketch it out for now and do the doc pull request and pics on the next Rock-ons UI update, it would be nice to have a sane  (may need some help there) and hopefully simple example of a Rockstor Plex setup out there.

**Comment by phillxnet** [comment]
fixed by merged pull request #53 . At least from installing the rock-on itself.
