### ISSUE TITLE
The requirements for the Tailscale service are not described 

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#471]
We currently do not list the requirements for the configuration of the Tailscale service:
- install the Tailscale repo 
- install the `tailscale` package

This might have already been needed by a user of the Testing channel: [https://forum.rockstor.com/t/unknown-internal-error-doing-a-post-to-api-sm-services-tailscaled-config/9418/2](https://forum.rockstor.com/t/unknown-internal-error-doing-a-post-to-api-sm-services-tailscaled-config/9418/2?u=flox).

We should provide a link to the Tailscale docs that provide clear step-by-step instructions: https://tailscale.com/download/linux/opensuse-leap-15.2

Note that this page has two methods:
- a pipe to bash script: this will handle up to Leap 15.5 and tumbleweed 
- manual install: this has a drop-down list of supported distros that unfortunately list only Leap 15.1 and 15.2 with tumbleweed. This is unfortunately outdated as the repos currently exist up to 15.5. Note that someone already reported this and the issue is marked as completed https://github.com/tailscale/tailscale/issues/9404).

---

Partner doc issue: https://github.com/rockstor/rockstor-core/issues/2845

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for creating this issue. From the context it does look like we need to have this doc entry in order to intercept and explain our two upstreams interincompatibility: i.e. the referenced Tailscale issue. It looks to me like that issue was accidentally closed actually.

**Comment by FroggyFlox** [comment]
> They now use, in those instructions, the a `$VERSION` env

If I remember correctly, their auto install script also uses the `$VERSION` variable for most of the supported distributions. This does seem like their favorite route of operation, indeed.

**Comment by phillxnet** [comment]
## State as of release of 15.6

From: https://tailscale.com/kb/1303/install-opensuse-leap

> https://pkgs.tailscale.com/stable/opensuse/leap/15.6/tailscale.repo

is still non-existent, and the Tail scale front page here: https://tailscale.com/ - Download (top menu) - scroll-down
has max Leap version of 15.2 !! So we have our docs point to the still outdated but years more relevant first link in this comment.

**Comment by phillxnet** [comment]
I'm going to tackle at least the first flush of this issue. I.e. adding to our existing Tailscale section the indicated need to install first:
https://rockstor.com/docs/interface/system/services.html#tailscale

And as from "Add Tailscale to list of features #461" #482
We no have the Tailscale upstream and our services page linked from our website index.

Give we already have a link to this doc section from within our current Web-UI thanks to @FroggyFlox via:

"Add/Update help icon linking to docs #2720" #2725

we can leverage this to point folks already to the reason they may encournter Tailscale config issues. This doc issues partner issue in rockstor-core can then enhance this further with more contextual feedback on the need to install Tailscale first.

**Comment by phillxnet** [comment]
Re:

> Give we already have a link to this doc section from within our current Web-UI thanks to @FroggyFlox via:

Our Web-UI embedded current doc links is as follows:
![Existing-link-to-docs](https://github.com/rockstor/rockstor-doc/assets/2521585/f880f88d-93e1-42c5-a5b9-d63848459f71)
