### ISSUE TITLE
Update V3 to V4 howto to also include V5

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#485]
The procedure, a re-install, pool import, and exported config save file upload and apply is identical in transitioning a legacy (CentOS based) V3 Rockstor to V4; as it is a V3 to V5.

It is proposed that we extend this migration from V3 howto, to also mention V5 given we have just released 5.0.14-0 (RC9) and so are close to our next Stable V5 repository for a "Built on openSUSE Leap" 15.6 derived installer. Such as we have had pre-build on our downloads page for some-time now.

---

Referenced howto:  https://rockstor.com/docs/howtos/v3_to_v4.html

**Comment by Hooverdan96** [comment]
Would it make sense to rename this section (and the underlying file and TOC reference) to `CentOS_to_OpenSUSE.rst` and adjust the document to represent "only" the transition from CentOS to OpenSUSE (since it won't matter whether one goes from v3.x to v4 or v5 (if anything, we need to add more warnings/notes with changes in v5 or eventual v6 over time).

The new heading could be simplified to something like this:
```
Migrating from Legacy V3 on CentOS to Latest "Built on openSUSE"
```

and then change the V4 reference to "latest" or whatever else makes sense, since the content is really for the changing "legs" (as you like to call it) of Rockstor. Or do you have something different in mind?

**Comment by phillxnet** [comment]
@Hooverdan96 I agree, mostly. But for the "Latest" wording. Maybe we just need to remove the specifics re V4, i.e. as you say we already have the "Built on openSUSE" reference. I.e.

> Migrating from Legacy V3 on CentOS to "Built on openSUSE" versions.

This then covers what we need, and will hopefully remain general enough for things like our TW variant. And we also the 'Leap' reference if need be.

Re:

> Would it make sense to rename this section (and the underlying file and TOC reference) to `CentOS_to_OpenSUSE.rst`

I think so. But we need to maintain our prior links, i.e. if we change/move stuff we have the facility, thanks to @FroggyFlox of maintaining a forwarding capability from the prior legacy links. This maintains compatibility with folks bookmarks or older internet links out there.

I.e. such as was last done in:

"Remove legacy "Mirroring Rockstor OS using Linux Raid" #466  #481

Take a look at https://github.com/rockstor/rockstor-doc/blob/master/redirects.txt where we maintain older links viability by redirecting to where-ever the new page is, or to what-ever we have re-named it to. This helps with keeping folks bookmarks and 3rd party external links into the docs valid.

I'm not keen on having this doc grow to be all V3 to what-ever comes in years to come however. Hence maintaining some reference to "Built on openSUSE" with likely also some reference to Leap 15.* & TW. Especially given Leap 16 looks like it may itself entail sufficient changes that it will need a doc of it's own. This docs focus is predominantly "from" CentOS V3: earlier also really, but we had V3 for so long that could stay here I think. And we have our existing intra Leap update docs. And will likely also need a Leap 15.* to Leap 16.* if we end up sticking with Leap and not simply focusing on TW only when that bridge appears on our immediate horizon.
