### ISSUE TITLE
Note that SMB export restore does not as-yet re-assert custom settings

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#487]
Indicate, specifically, that we do not, as-yet, restore custom SMB settings via the procedure indicated in the following doc section:

https://rockstor.com/docs/interface/system/config_backup.html

Relevant to this issue; we currently indicate, under **The following state information is saved as part of a backup**:

> - Samba configuration and exports

This should contain a caveat that we do not yet restore custom config (but we do save it).

---

We have, by way of future-feature issue by @Hooverdan96  https://github.com/rockstor/rockstor-core/issues/2905 this short-coming detailed.

**Comment by Hooverdan96** [comment]
Thanks for this. We want to clarify that the custom settings at the share level are not restored, I believe the global SMB config actually is.
