### ISSUE TITLE
Analytics documentation

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#5]

**Comment by phillxnet** [comment]
Document the currently available analytics as per:
"We hope to further detail existing NFS analytics in the near future."
in http://rockstor.com/docs/analytics.html (of analytics.rst)

**Comment by FroggyFlox** [comment]
@phillxnet, is this issue still valid?
`analytics.rst` was deleted in #284, for instance, and I don't know if the reference to NFS we currently have in `introduction/features.rst` is still relevant (I'm not sure I know what it refers to).

**Comment by phillxnet** [comment]
@FroggyFlox 
I've never actually looked into this myself unfortunately. But wondered about it from time to time. I've had zero feedback on it's state/function so assumed it was either planned as a feature and never actually existed, or no one ever actually used it if it does exist. Sorry but it's just never come up either here, on the forum, or in support email. And given this, and that we've had no issues raised I've not gotten around to actually looking into the state of the code in this area at all.

I say we close this to tidy up as given it's popularity and potential non existence, if it comes up again we can always re-open. Also it's from 2013 originally ! I'd just always assumed we had some form of analytics that I'd just not seen yet.

**Comment by FroggyFlox** [comment]
You seem to be describing exactly my impressions on this. I can't remember whether I saw such reference in rockstor's code itself so we can always see.


> I say we close this to tidy up as given it's popularity and potential non existence, if it comes up again we can always re-open. Also it's from 2013 originally ! I'd just always assumed we had some form of analytics that I'd just not seen yet.

Sounds good. Do you think we should also remove the mention of this we have in the docs? It's mainly a small section in `introduction/features.rst` and then a mention of "Analytics" in one or two spots, I believe.

**Comment by phillxnet** [comment]
@FroggyFlox Re:
> Do you think we should also remove the mention of this we have in the docs?

I think we should establish if this feature actually exists. If so then it's existing doc reference could prompt someone to contribute and fill in the details. If it doesn't exist in code then we delete it's currently near empty reference within the docs.

I.E. There has been no apparent interest in that area of code or docs so if no code then no docs is good. Otherwise we should leave it's doc reference as a 'prompt'.

**Comment by FroggyFlox** [comment]
> I think we should establish if this feature actually exists. If so then it's existing doc reference could prompt someone to contribute and fill in the details. If it doesn't exist in code then we delete it's currently near empty reference within the docs.

The following issue is of interest here and seems to indicate NFS analytics are indeed not-present (with the caveat that this is an old issue too):
https://github.com/rockstor/rockstor-doc/issues/137#issue-146450504

**Comment by phillxnet** [comment]
@FroggyFlox Re:

> are indeed not-present

Nice find. And that was after my own association with the project began so I think we are safe to assume this is a non existent feature :) . A good reminder that doc entries should follow features; not the other way around. A doc entry does not a feature make, even if it's just a 'place-holder'.

**Comment by phillxnet** [comment]
Closing as per recent discussion here.
