### ISSUE TITLE
Tailscale install how-to needs to be updated for Leap 15.6

### ISSUE THREAD

**Issue by FroggyFlox** [rockstor/rockstor-doc#512]
As of just a few days ago, an official Tailscale repo for Leap 15.6 is available. This should thus be the recommended way to install tailscale in our how-to install tailscale document (https://rockstor.com/docs/howtos/tailscale_install.html#install-tailscale). As a reminder, we currently recommend to use the Leap 15.5 repository as the Leap 15.6 was not available yet (see https://github.com/rockstor/rockstor-doc/issues/471 for context).

Announcement and closure of the related Tailscale issue: https://github.com/tailscale/tailscale/issues/12541#issuecomment-2508245558

**Comment by phillxnet** [comment]
@FroggyFlox Thanks for keeping an eye on that, and apparently at this issue's creation time their generic linux install instructions had yet to be updated accordingly; however as of yesterday it seems they have also now seen to this:

see: https://github.com/tailscale/tailscale/issues/12541#issuecomment-2512186244

> One last update here: https://tailscale.com/download has been updated to include install instructions for versions 15.3 through 15.6 (also linkable directly via https://tailscale.com/download/linux/opensuse-leap-15.6)
