### ISSUE TITLE
add reinstall howto

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#61]
A small howto detailing the re-installation process, ie extra steps needed during installer.
Also a note about importing data from previous Rockstor data disks.
Once in could also be a place to detail the future feature of config save and restore.

**Comment by phillxnet** [comment]
I am working on a pull request for this now.

**Comment by phillxnet** [comment]
Pull request #62 ready for review.

**Comment by phillxnet** [comment]
Tried to re-do pull request to get easier merge button so now #63 is the pull request ready for review.

**Comment by schakrava** [comment]
Fixed by #63
