### ISSUE TITLE
sphinx and subdirectories

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#64]
for some documents like rocksons and reinstall, we are using subdirectories which is breaking the links to  the logo. We need to figure out the right sphinx config changes so it populates the static files correctly.

**Comment by phillxnet** [comment]
OK, thanks for point this out. I will have a look into it.  It was part of the reason I shied away from restructuring, being completely new to sphinx and rst and not sure of the knock-ons.  If anyone knows how to fix this then please chip in.

Indicator is lost Rockstor icon in top left corner of web page rendering of this Documentation at:-
http://rockstor.com/docs/docker-based-rock-ons/overview.html
and
http://rockstor.com/docs/reinstall/reinstall.html

as opposed to for example:-
http://rockstor.com/docs/contribute.html
where the Rockstor (top left) icon is visible.

**Comment by phillxnet** [comment]
On first investigation I suspect this is hardwired into our theme but not certain; in themes/layout.html
```
            <a href="/"><img src="_static/img/rockstorlogo-font2.png" style="padding-top: 8px;" width="150px">
```
and I found "Fix logo relative path" in a pull request on another themes:-
https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/80
https://github.com/ryan-roemer/sphinx-bootstrap-theme/commit/2bfddcbef280c615989a657377d7e0f42a12badb
and from that commit in that pull request we have:-
```
{%- if logo %}<img src="_static/{{ logo }}">{%- endif %}
changed to:-
{%- if logo %}<img src="{{ pathto('_static/' + logo, 1) }}">{%- endif %}
```
however we don't have these mechanisms in place.  Pointers anyone.
I will have another look soon.

**Comment by phillxnet** [comment]
New subdirectory structure (ie rockons and reinstall sections) also break favicon and community dropdown.
Fix found and submitting pull request shortly.

**Comment by phillxnet** [comment]
Pull request #72 ready for review.
Should also fix recently found community menu broken in sub directory sections.
