### ISSUE TITLE
document config backups

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-doc#68]
As a new neat and key feature I'd like to see this referenced in the documentation; I will try and prepare a pull request for this tomorrow (UK).
I am planning to add this at least as a section in the existing "Reinstalling Rockstor" howto.

**Comment by schakrava** [comment]
Thanks @phillxnet That would be great! Note that the popups in the UI will be improved in the future, so as you document feel free to suggest improvements.

**Comment by phillxnet** [comment]
I am currently working on a pull request for this issue.

**Comment by phillxnet** [comment]
- During restore I think popup "It may take a bit ..." should be "This may take a while ..."
- I think the choose file box should be a little longer as one can't see the whole default file name after an upload file pick; although it is displayed in full with the mouse over there after.
Those are the only things that jumped out at me.
Nice job @schakrava @gkadillak

**Comment by phillxnet** [comment]
Pull request #69 ready for review.

**Comment by phillxnet** [comment]
Closing as referenced pull request is now merged.
