### ISSUE TITLE
user configuration

### ISSUE THREAD

**Issue by schakrava** [rockstor/rockstor-doc#8]

**Comment by phillxnet** [comment]
This issue could now be used to indicate an update to the user config as it exists but is now rather old.

**Comment by FroggyFlox** [comment]
@phillxnet, I have noticed we do not seem to have documentation on the "_Groups_" configuration feature. As the latter is rather small, I was thinking we could take the opportunity to add it to the "User configuration" documentation page and update it at the same time.

This would thus lead to a "Users and Groups configuration" page. Maybe we could even simplify this heading to "Users and Groups".

**Comment by phillxnet** [comment]
> Maybe we could even simplify this heading to "Users and Groups".

Sound great. The simpler we can put it the better.

**Comment by phillxnet** [comment]
Closing as repo clean-up. @FroggyFlox we might want to open a new issue re your suggestion:

> This would thus lead to a "Users and Groups configuration" page. Maybe we could even simplify this heading to "Users and Groups".

**Comment by FroggyFlox** [comment]
@phillxnet , thanks for taking care of this. I agree with you with regards to opening more focused issue(s). We actually have a couple pages in such case post #290 so I'll get to identify and list them in their separate issues.
